In [36]:
import pandas as pd

# Load the already filtered bank data from the CSV file
file_path = '/content/filtered_bank_data.csv'
filtered_bank_data = pd.read_csv(file_path)

# Ensure the 'Date' column is in datetime format
filtered_bank_data['Date'] = pd.to_datetime(filtered_bank_data['Date'])

# Display the first few rows of the filtered data and its info
display(filtered_bank_data.head())
print(filtered_bank_data.info())
print(f"Data loaded from {file_path}. Total rows: {len(filtered_bank_data)}")

        Date        Bank
0 2020-01-02  632.707775
1 2020-01-03  632.707775
2 2020-01-06  628.686327
3 2020-01-07  612.600536
4 2020-01-08  589.812332

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1400 entries, 0 to 1399
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1400 non-null   datetime64[ns]
 1   Bank    1400 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 22.0 KB
None
Data loaded from /content/filtered_bank_data.csv. Total rows: 1400

In [35]:
# Save the filtered DataFrame to a new CSV file
output_file_path = '/content/filtered_bank_data.csv'
filtered_df.to_csv(output_file_path, index=False)
print(f"Filtered data saved to {output_file_path}")

NameError: name 'filtered_df' is not defined

In [6]:
# Load the new CSV file
new_file_path = '/content/ccpi_yoy.csv'
df_new = pd.read_csv(new_file_path)

# Display the first few rows and column names to understand the structure
display(df_new.head())
print(df_new.columns)

   Year     Month      Base  YoY_Inflation_%
0  2015   January  2013=100              3.8
1  2015  February  2013=100              1.9
2  2015     March  2013=100              1.5
3  2015     April  2013=100              1.4
4  2015       May  2013=100              1.5

Index(['Year', 'Month', 'Base', 'YoY_Inflation_%'], dtype='object')

In [7]:
# Combine 'Year' and 'Month' to create a 'Date' column
df_new['Date'] = pd.to_datetime(df_new['Year'].astype(str) + '-' + df_new['Month'], format='%Y-%B')

# Define the start and end dates for filtering (same as before)
start_date = pd.to_datetime('2020-01-01')
end_date = pd.to_datetime('2025-12-31')

# Filter the DataFrame for the desired date range
filtered_ccpi_df = df_new[(df_new['Date'] >= start_date) & (df_new['Date'] <= end_date)]

# Display the first few rows of the filtered data and its info
display(filtered_ccpi_df.head())
print(filtered_ccpi_df.info())
print(f"Data filtered from {start_date.date()} to {end_date.date()}. Total rows: {len(filtered_ccpi_df)}")

    Year     Month      Base  YoY_Inflation_%       Date
60  2020   January  2013=100              5.7 2020-01-01
61  2020  February  2013=100              6.2 2020-02-01
62  2020     March  2013=100              5.4 2020-03-01
63  2020     April  2013=100              5.2 2020-04-01
64  2020       May  2013=100              4.0 2020-05-01

<class 'pandas.core.frame.DataFrame'>
Index: 72 entries, 60 to 131
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             72 non-null     int64
 1   Month            72 non-null     object
 2   Base             72 non-null     object
 3   YoY_Inflation_%  72 non-null     float64
 4   Date             72 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 3.4+ KB
None
Data filtered from 2020-01-01 to 2025-12-31. Total rows: 72

In [10]:
# Load the new exchange rate CSV file
exchange_rate_file_path = '/content/exchange rate.csv'
df_exchange_rate = pd.read_csv(exchange_rate_file_path)

# Display the first few rows and column names to understand the structure
display(df_exchange_rate.head())
print(df_exchange_rate.columns)

  Currency        Date  Exchange Rate
0      USD  2025-12-31       309.9944
1      USD  2025-12-30       309.8309
2      USD  2025-12-29       309.7101
3      USD  2025-12-26       309.7074
4      USD  2025-12-24       309.6580

Index(['Currency', 'Date', 'Exchange Rate'], dtype='object')

In [11]:
# Convert the 'Date' column to datetime objects
df_exchange_rate['Date'] = pd.to_datetime(df_exchange_rate['Date'], errors='coerce')

# Define the start and end dates for filtering
start_date = pd.to_datetime('2020-01-01')
end_date = pd.to_datetime('2025-12-31')

# Filter the DataFrame for the desired date range
filtered_exchange_rate_df = df_exchange_rate[(df_exchange_rate['Date'] >= start_date) & (df_exchange_rate['Date'] <= end_date)]

# Display the first few rows of the filtered data and its info
display(filtered_exchange_rate_df.head())
print(filtered_exchange_rate_df.info())
print(f"Exchange rate data filtered from {start_date.date()} to {end_date.date()}. Total rows: {len(filtered_exchange_rate_df)}")

  Currency       Date  Exchange Rate
0      USD 2025-12-31       309.9944
1      USD 2025-12-30       309.8309
2      USD 2025-12-29       309.7101
3      USD 2025-12-26       309.7074
4      USD 2025-12-24       309.6580

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1445 entries, 0 to 1444
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Currency       1445 non-null   object
 1   Date           1445 non-null   datetime64[ns]
 2   Exchange Rate  1445 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 34.0+ KB
None
Exchange rate data filtered from 2020-01-01 to 2025-12-31. Total rows: 1445

In [12]:
# Save the filtered exchange rate data to a new CSV file
exchange_rate_output_file_path = '/content/filtered_exchange_rate_data.csv'
filtered_exchange_rate_df.to_csv(exchange_rate_output_file_path, index=False)
print(f"Filtered exchange rate data saved to {exchange_rate_output_file_path}")

Filtered exchange rate data saved to /content/filtered_exchange_rate_data.csv

In [8]:
# Drop the 'Year', 'Month', and 'Base' columns
filtered_ccpi_df = filtered_ccpi_df.drop(columns=['Year', 'Month', 'Base'])

# Display the first few rows of the modified DataFrame
display(filtered_ccpi_df.head())

    YoY_Inflation_%       Date
60              5.7 2020-01-01
61              6.2 2020-02-01
62              5.4 2020-03-01
63              5.2 2020-04-01
64              4.0 2020-05-01

In [9]:
# Save the filtered CCPI data to a new CSV file
ccpi_output_file_path = '/content/filtered_ccpi_data.csv'
filtered_ccpi_df.to_csv(ccpi_output_file_path, index=False)
print(f"Filtered CCPI data saved to {ccpi_output_file_path}")

Filtered CCPI data saved to /content/filtered_ccpi_data.csv

### Merging Annual Data Files

I will now load the individual annual data files, standardize their date columns, and merge them into a single DataFrame. This will allow for a comprehensive view of the data across all specified years.

In [19]:
import pandas as pd

file_path_2020 = '/content/2020 Data.xls'

# Load the 2020 Data.xls file, assuming header is at row 3 (0-indexed) and date column is 'TRADING DATE'
df_2020 = pd.read_excel(file_path_2020, header=3)

# Clean column names by stripping whitespace
df_2020.columns = df_2020.columns.str.strip()

# Convert the 'TRADING DATE' column to datetime objects, coercing errors
df_2020['TRADING DATE'] = pd.to_datetime(df_2020['TRADING DATE'], errors='coerce')

# Drop rows where 'TRADING DATE' is NaT (if any)
df_2020.dropna(subset=['TRADING DATE'], inplace=True)

# Convert the 'TRADING DATE' column to ISO 8601 (YYYY-MM-DD) string format
df_2020['TRADING DATE'] = df_2020['TRADING DATE'].dt.strftime('%Y-%m-%d')

print(f"Processed file: {file_path_2020}")
print("DataFrame after date conversion:")
display(df_2020.head())
df_2020.info()

Processed file: /content/2020 Data.xls
DataFrame after date conversion:

/tmp/ipykernel_3006/2744506231.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_2020['TRADING DATE'] = pd.to_datetime(df_2020['TRADING DATE'], errors='coerce')

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,AAF,N,0,ASIA ASSET,2020-01-02,8.80,8.50,8.60,8.80,7,522,4500.1
1,AAF,N,0,ASIA ASSET,2020-01-03,8.60,8.50,8.50,8.60,10,15582,132517.0
2,AAF,N,0,ASIA ASSET,2020-01-06,8.50,8.50,8.50,8.50,3,200,1700.0
3,AAF,N,0,ASIA ASSET,2020-01-07,8.40,8.30,8.30,8.40,6,700,5844.0
4,AAF,N,0,ASIA ASSET,2020-01-08,8.50,8.10,8.10,8.30,13,15926,129859.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50925 entries, 0 to 50924
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   COMPANY ID          50925 non-null  object
 1   MAIN TYPE           50925 non-null  object
 2   SUB TYPE            50925 non-null  int64
 3   SHORT NAME          50925 non-null  object
 4   TRADING DATE        50925 non-null  object
 5   PRICE HIGH (Rs.)    50925 non-null  object
 6   PRICE LOW (Rs.)     50925 non-null  object
 7   CLOSE PRICE (Rs.)   50925 non-null  object
 8   OPEN PRICE (Rs.)    50925 non-null  object
 9   TRADE VOLUME (No.)  50925 non-null  int64
 10  SHARE VOLUME (No.)  50925 non-null  int64
 11  TURNOVER (Rs.)      50925 non-null  float64
dtypes: float64(1), int64(3), object(8)
memory usage: 4.7+ MB

In [20]:
print("First 5 dates:")
display(df_2020['TRADING DATE'].head())
print("\nLast 5 dates:")
display(df_2020['TRADING DATE'].tail())

First 5 dates:

0    2020-01-02
1    2020-01-03
2    2020-01-06
3    2020-01-07
4    2020-01-08
Name: TRADING DATE, dtype: object

Last 5 dates:

50920    2020-12-23
50921    2020-12-24
50922    2020-12-28
50923    2020-12-30
50924    2020-12-31
Name: TRADING DATE, dtype: object

In [32]:
import pandas as pd

file_path_2021 = '/content/2021 Data.xls'

# Load all sheets from the 2021 Data.xls file
# sheet_name=None returns a dictionary of DataFrames, one for each sheet
all_sheets_2021 = pd.read_excel(file_path_2021, sheet_name=None, header=3)

processed_dfs = []

for sheet_name, df_sheet in all_sheets_2021.items():
    # Ensure the sheet is not empty and contains enough rows for header processing
    if not df_sheet.empty and len(df_sheet) > 0:
        # Set the column names using the first row of the DataFrame (which contains the actual headers)
        # Make a copy to avoid SettingWithCopyWarning later
        df_sheet_copy = df_sheet.copy()
        df_sheet_copy.columns = df_sheet_copy.iloc[0]

        # Drop the first row as it has now become the header
        df_sheet_copy = df_sheet_copy[1:].reset_index(drop=True)

        # Clean column names by stripping whitespace
        df_sheet_copy.columns = df_sheet_copy.columns.str.strip()

        # Convert the 'TRADING DATE' column to datetime objects, coercing errors
        # Only attempt conversion if 'TRADING DATE' column exists
        if 'TRADING DATE' in df_sheet_copy.columns:
            df_sheet_copy['TRADING DATE'] = pd.to_datetime(df_sheet_copy['TRADING DATE'], errors='coerce')

            # Drop rows where 'TRADING DATE' is NaT (if any)
            df_sheet_copy.dropna(subset=['TRADING DATE'], inplace=True)

            # Convert the 'TRADING DATE' column to ISO 8601 (YYYY-MM-DD) string format
            df_sheet_copy['TRADING DATE'] = df_sheet_copy['TRADING DATE'].dt.strftime('%Y-%m-%d')
            processed_dfs.append(df_sheet_copy)

# Concatenate all processed DataFrames into a single df_2021
df_2021 = pd.concat(processed_dfs, ignore_index=True)

print(f"Processed file: {file_path_2021} from all sheets")
print("DataFrame after date conversion and concatenation:")
display(df_2021.head())
df_2021.info()

Processed file: /content/2021 Data.xls from all sheets
DataFrame after date conversion and concatenation:

/tmp/ipykernel_3006/1027011065.py:28: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_sheet_copy['TRADING DATE'] = pd.to_datetime(df_sheet_copy['TRADING DATE'], errors='coerce')
/tmp/ipykernel_3006/1027011065.py:28: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_sheet_copy['TRADING DATE'] = pd.to_datetime(df_sheet_copy['TRADING DATE'], errors='coerce')
/tmp/ipykernel_3006/1027011065.py:28: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_sheet_copy['TRADING DATE'] = pd.to_datetime(df_sheet_copy['TRADING DATE'], errors='coerce')

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,AAF,N,0000,ASIA ASSET,2021-01-04,8.90,8.80,8.80,8.80,4,2510,22208
1,AAF,N,0000,ASIA ASSET,2021-01-05,9.10,8.80,9.00,9.00,21,23269,206917.5
2,AAF,N,0000,ASIA ASSET,2021-01-06,9.00,8.80,8.80,8.80,28,22515,198242
3,AAF,N,0000,ASIA ASSET,2021-01-07,9.10,8.80,8.90,8.90,10,14832,131349.6
4,AAF,N,0000,ASIA ASSET,2021-01-08,8.80,8.60,8.60,8.60,24,109384,945862.3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46354 entries, 0 to 46353
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   COMPANY ID          46354 non-null  object
 1   MAIN TYPE           46354 non-null  object
 2   SUB TYPE            46354 non-null  object
 3   SHORT NAME          46354 non-null  object
 4   TRADING DATE        46354 non-null  object
 5   PRICE HIGH (Rs.)    46354 non-null  object
 6   PRICE LOW (Rs.)     46354 non-null  object
 7   CLOSE PRICE (Rs.)   46354 non-null  object
 8   OPEN PRICE (Rs.)    46354 non-null  object
 9   TRADE VOLUME (No.)  46354 non-null  object
 10  SHARE VOLUME (No.)  46354 non-null  object
 11  TURNOVER (Rs.)      46354 non-null  object
dtypes: object(12)
memory usage: 4.2+ MB

In [33]:
print("First 5 rows of 2021 Data.xls:")
display(df_2021.head())
print("\nLast 5 rows of 2021 Data.xls:")
display(df_2021.tail())

First 5 rows of 2021 Data.xls:

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,AAF,N,0000,ASIA ASSET,2021-01-04,8.90,8.80,8.80,8.80,4,2510,22208
1,AAF,N,0000,ASIA ASSET,2021-01-05,9.10,8.80,9.00,9.00,21,23269,206917.5
2,AAF,N,0000,ASIA ASSET,2021-01-06,9.00,8.80,8.80,8.80,28,22515,198242
3,AAF,N,0000,ASIA ASSET,2021-01-07,9.10,8.80,8.90,8.90,10,14832,131349.6
4,AAF,N,0000,ASIA ASSET,2021-01-08,8.80,8.60,8.60,8.60,24,109384,945862.3

Last 5 rows of 2021 Data.xls:

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
46349,YORK,N,0000,YORK ARCADE,2021-12-27,225.00,215.00,215.00,220.00,24,509,110151.25
46350,YORK,N,0000,YORK ARCADE,2021-12-28,223.00,213.75,215.00,223.00,5,74,15874.5
46351,YORK,N,0000,YORK ARCADE,2021-12-29,219.00,212.50,213.50,219.00,16,273,58347.25
46352,YORK,N,0000,YORK ARCADE,2021-12-30,219.00,213.00,213.50,218.00,5,35,7542.75
46353,YORK,N,0000,YORK ARCADE,2021-12-31,212.25,210.00,210.50,212.25,27,469,98796.5

In [35]:
file_path_2022 = '/content/2022 Data.xls'

# Load all sheets from the 2022 Data.xls file
# sheet_name=None returns a dictionary of DataFrames, one for each sheet
all_sheets_2022 = pd.read_excel(file_path_2022, sheet_name=None, header=3)

processed_dfs_2022 = []

for sheet_name, df_sheet in all_sheets_2022.items():
    # Ensure the sheet is not empty and contains enough rows for header processing
    if not df_sheet.empty and len(df_sheet) > 0:
        # Set the column names using the first row of the DataFrame (which contains the actual headers)
        # Make a copy to avoid SettingWithCopyWarning later
        df_sheet_copy = df_sheet.copy()
        df_sheet_copy.columns = df_sheet_copy.iloc[0]

        # Drop the first row as it has now become the header
        df_sheet_copy = df_sheet_copy[1:].reset_index(drop=True)

        # Clean column names by stripping whitespace
        df_sheet_copy.columns = df_sheet_copy.columns.str.strip()

        # Convert the 'TRADING DATE' column to datetime objects, coercing errors
        # Only attempt conversion if 'TRADING DATE' column exists
        if 'TRADING DATE' in df_sheet_copy.columns:
            df_sheet_copy['TRADING DATE'] = pd.to_datetime(df_sheet_copy['TRADING DATE'], errors='coerce')

            # Drop rows where 'TRADING DATE' is NaT (if any)
            df_sheet_copy.dropna(subset=['TRADING DATE'], inplace=True)

            # Convert the 'TRADING DATE' column to ISO 8601 (YYYY-MM-DD) string format
            df_sheet_copy['TRADING DATE'] = df_sheet_copy['TRADING DATE'].dt.strftime('%Y-%m-%d')
            processed_dfs_2022.append(df_sheet_copy)

# Concatenate all processed DataFrames into a single df_2022
df_2022 = pd.concat(processed_dfs_2022, ignore_index=True)

print(f"Processed file: {file_path_2022} from all sheets")
print("DataFrame after date conversion and concatenation:")
display(df_2022.head())
df_2022.info()

Processed file: /content/2022 Data.xls from all sheets
DataFrame after date conversion and concatenation:

/tmp/ipykernel_3006/825129317.py:26: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_sheet_copy['TRADING DATE'] = pd.to_datetime(df_sheet_copy['TRADING DATE'], errors='coerce')
/tmp/ipykernel_3006/825129317.py:26: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_sheet_copy['TRADING DATE'] = pd.to_datetime(df_sheet_copy['TRADING DATE'], errors='coerce')

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,AAF,N,0000,ASIA ASSET,2022-01-03,9.00,8.20,8.50,8.40,67,195403,1727142.6
1,AAF,N,0000,ASIA ASSET,2022-01-04,8.50,8.10,8.50,8.50,53,132677,1114958.4
2,AAF,N,0000,ASIA ASSET,2022-01-05,9.60,8.50,8.90,8.50,378,1393358,12749459.8
3,AAF,N,0000,ASIA ASSET,2022-01-06,11.00,8.70,10.20,9.00,460,2087387,20763503
4,AAF,N,0000,ASIA ASSET,2022-01-07,10.50,9.50,10.10,10.40,160,580725,5899162.2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28466 entries, 0 to 28465
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   COMPANY ID          28466 non-null  object
 1   MAIN TYPE           28466 non-null  object
 2   SUB TYPE            28466 non-null  object
 3   SHORT NAME          28466 non-null  object
 4   TRADING DATE        28466 non-null  object
 5   PRICE HIGH (Rs.)    28466 non-null  object
 6   PRICE LOW (Rs.)     28466 non-null  object
 7   CLOSE PRICE (Rs.)   28466 non-null  object
 8   OPEN PRICE (Rs.)    28466 non-null  object
 9   TRADE VOLUME (No.)  28466 non-null  object
 10  SHARE VOLUME (No.)  28466 non-null  object
 11  TURNOVER (Rs.)      28466 non-null  object
dtypes: object(12)
memory usage: 2.6+ MB

In [36]:
print("First 5 rows of df_2022:")
display(df_2022.head())
print("\nLast 5 rows of df_2022:")
display(df_2022.tail())

First 5 rows of df_2022:

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,AAF,N,0000,ASIA ASSET,2022-01-03,9.00,8.20,8.50,8.40,67,195403,1727142.6
1,AAF,N,0000,ASIA ASSET,2022-01-04,8.50,8.10,8.50,8.50,53,132677,1114958.4
2,AAF,N,0000,ASIA ASSET,2022-01-05,9.60,8.50,8.90,8.50,378,1393358,12749459.8
3,AAF,N,0000,ASIA ASSET,2022-01-06,11.00,8.70,10.20,9.00,460,2087387,20763503
4,AAF,N,0000,ASIA ASSET,2022-01-07,10.50,9.50,10.10,10.40,160,580725,5899162.2

Last 5 rows of df_2022:

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
28461,YORK,N,0000,YORK ARCADE,2022-06-20,144.50,129.25,129.75,132.00,7,131,17004.25
28462,YORK,N,0000,YORK ARCADE,2022-06-21,151.00,151.00,129.75,151.00,1,1,151
28463,YORK,N,0000,YORK ARCADE,2022-06-23,148.50,148.50,129.75,148.50,1,1,148.5
28464,YORK,N,0000,YORK ARCADE,2022-06-27,148.00,148.00,129.75,148.00,1,1,148
28465,YORK,N,0000,YORK ARCADE,2022-06-30,144.00,143.75,129.75,144.00,4,6,862.75

In [39]:
file_path_2023 = '/content/2023 Data.csv'

# Load the CSV file, assuming header is at row 2 (0-indexed)
df_2023 = pd.read_csv(file_path_2023, header=2)

# Clean column names by stripping whitespace
df_2023.columns = df_2023.columns.str.strip()

# Drop any unnamed columns that might arise from extra delimiters in the CSV
df_2023 = df_2023.loc[:, ~df_2023.columns.str.contains('^Unnamed')]

# Convert the 'TRADING DATE' column to datetime objects, coercing errors
df_2023['TRADING DATE'] = pd.to_datetime(df_2023['TRADING DATE'], errors='coerce')

# Drop rows where 'TRADING DATE' is NaT (if any)
df_2023.dropna(subset=['TRADING DATE'], inplace=True)

# Convert the 'TRADING DATE' column to ISO 8601 (YYYY-MM-DD) string format
df_2023['TRADING DATE'] = df_2023['TRADING DATE'].dt.strftime('%Y-%m-%d')

print(f"Processed file: {file_path_2023}")
print("DataFrame after date conversion:")
display(df_2023.head())
df_2023.info()

Processed file: /content/2023 Data.csv
DataFrame after date conversion:

/tmp/ipykernel_3006/2366673057.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_2023['TRADING DATE'] = pd.to_datetime(df_2023['TRADING DATE'], errors='coerce')

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,AAF,N,0,ASIA ASSET,2023-01-02,8.0,8.0,7.7,8.0,1,1,8.00
1,AAF,N,0,ASIA ASSET,2023-01-03,7.9,7.5,7.7,7.9,4,"10,261","78,909.90"
2,AAF,N,0,ASIA ASSET,2023-01-04,7.8,7.6,7.6,7.6,2,"10,010","76,078.00"
3,AAF,N,0,ASIA ASSET,2023-01-05,7.8,7.8,7.6,7.8,2,51,397.80
4,AAF,N,0,ASIA ASSET,2023-01-09,8.7,7.4,8.5,7.5,71,"189,980","1,595,930.90"

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62501 entries, 0 to 62500
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   COMPANY ID          62501 non-null  object
 1   MAIN TYPE           62501 non-null  object
 2   SUB TYPE            62501 non-null  int64
 3   SHORT NAME          62501 non-null  object
 4   TRADING DATE        62501 non-null  object
 5   PRICE HIGH (Rs.)    62501 non-null  float64
 6   PRICE LOW (Rs.)     62493 non-null  float64
 7   CLOSE PRICE (Rs.)   62501 non-null  float64
 8   OPEN PRICE (Rs.)    62496 non-null  float64
 9   TRADE VOLUME (No.)  62501 non-null  object
 10  SHARE VOLUME (No.)  62501 non-null  object
 11  TURNOVER (Rs.)      62501 non-null  object
dtypes: float64(4), int64(1), object(7)
memory usage: 5.7+ MB

In [38]:
print("First 5 rows of df_2023:")
display(df_2023.head())
print("\nLast 5 rows of df_2023:")
display(df_2023.tail())

First 5 rows of df_2023:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,"DAILY HIGH, LOW AND CLOSING PRICES 2023 (Janua...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.),NaN,NaN,NaN,NaN
3,AAF,N,0,ASIA ASSET,2-Jan-23,8.00,8.00,7.70,8.00,1,1,8.00,NaN,NaN,NaN,NaN
4,AAF,N,0,ASIA ASSET,3-Jan-23,7.90,7.50,7.70,7.90,4,"10,261","78,909.90",NaN,NaN,NaN,NaN

Last 5 rows of df_2023:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
62499,YORK,N,0,YORK ARCADE,13-Dec-23,151.75,151.25,149.75,151.75,3,9,"1,363.00",NaN,NaN,NaN,NaN
62500,YORK,N,0,YORK ARCADE,18-Dec-23,151.0,151.0,151.0,151.0,7,200,"30,200.00",NaN,NaN,NaN,NaN
62501,YORK,N,0,YORK ARCADE,21-Dec-23,150.75,150.75,151.0,150.75,2,3,452.25,NaN,NaN,NaN,NaN
62502,YORK,N,0,YORK ARCADE,22-Dec-23,151.25,151.0,151.0,151.25,2,80,"12,080.50",NaN,NaN,NaN,NaN
62503,YORK,N,0,YORK ARCADE,29-Dec-23,145.25,145.25,151.0,145.25,1,4,581.00,NaN,NaN,NaN,NaN

In [40]:
print("First 5 rows of df_2023:")
display(df_2023.head())

First 5 rows of df_2023:

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,AAF,N,0,ASIA ASSET,2023-01-02,8.0,8.0,7.7,8.0,1,1,8.00
1,AAF,N,0,ASIA ASSET,2023-01-03,7.9,7.5,7.7,7.9,4,"10,261","78,909.90"
2,AAF,N,0,ASIA ASSET,2023-01-04,7.8,7.6,7.6,7.6,2,"10,010","76,078.00"
3,AAF,N,0,ASIA ASSET,2023-01-05,7.8,7.8,7.6,7.8,2,51,397.80
4,AAF,N,0,ASIA ASSET,2023-01-09,8.7,7.4,8.5,7.5,71,"189,980","1,595,930.90"

In [43]:
file_path_2024 = '/content/2024 Data.xls'

# Load all sheets from the 2024 Data.xls file
# sheet_name=None returns a dictionary of DataFrames, one for each sheet
all_sheets_2024 = pd.read_excel(file_path_2024, sheet_name=None, header=3)

processed_dfs_2024 = []

for sheet_name, df_sheet in all_sheets_2024.items():
    # Ensure the sheet is not empty and contains enough rows for header processing
    if not df_sheet.empty:
        df_sheet_copy = df_sheet.copy()

        # Clean column names by stripping whitespace
        df_sheet_copy.columns = df_sheet_copy.columns.str.strip()

        # Convert the 'TRADING DATE' column to datetime objects, coercing errors
        # Only attempt conversion if 'TRADING DATE' column exists
        if 'TRADING DATE' in df_sheet_copy.columns:
            df_sheet_copy['TRADING DATE'] = pd.to_datetime(df_sheet_copy['TRADING DATE'], errors='coerce')

            # Drop rows where 'TRADING DATE' is NaT (if any)
            df_sheet_copy.dropna(subset=['TRADING DATE'], inplace=True)

            # Convert the 'TRADING DATE' column to ISO 8601 (YYYY-MM-DD) string format
            df_sheet_copy['TRADING DATE'] = df_sheet_copy['TRADING DATE'].dt.strftime('%Y-%m-%d')
            processed_dfs_2024.append(df_sheet_copy)

# Concatenate all processed DataFrames into a single df_2024
df_2024 = pd.concat(processed_dfs_2024, ignore_index=True)

print(f"Processed file: {file_path_2024} from all sheets")
print("DataFrame after date conversion and concatenation:")
display(df_2024.head())
df_2024.info()

Processed file: /content/2024 Data.xls from all sheets
DataFrame after date conversion and concatenation:

/tmp/ipykernel_3006/3372956160.py:20: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_sheet_copy['TRADING DATE'] = pd.to_datetime(df_sheet_copy['TRADING DATE'], errors='coerce')

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,AAF,N,0,ASIA ASSET,2024-01-04,12.00,12.00,12.00,12.00,3,1452,17424.0
1,AAF,N,0,ASIA ASSET,2024-01-05,12.50,12.00,12.50,12.00,4,23400,281550.0
2,AAF,N,0,ASIA ASSET,2024-01-09,12.00,12.00,12.00,12.00,4,20000,240000.0
3,AAF,N,0,ASIA ASSET,2024-01-12,12.50,12.00,12.00,12.00,2,111,1337.5
4,AAF,N,0,ASIA ASSET,2024-01-16,12.00,12.00,12.00,12.00,1,2000,24000.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63332 entries, 0 to 63331
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   COMPANY ID          63332 non-null  object
 1   MAIN TYPE           63332 non-null  object
 2   SUB TYPE            63332 non-null  int64
 3   SHORT NAME          63332 non-null  object
 4   TRADING DATE        63332 non-null  object
 5   PRICE HIGH (Rs.)    63327 non-null  object
 6   PRICE LOW (Rs.)     63295 non-null  object
 7   CLOSE PRICE (Rs.)   63332 non-null  object
 8   OPEN PRICE (Rs.)    63312 non-null  object
 9   TRADE VOLUME (No.)  63332 non-null  int64
 10  SHARE VOLUME (No.)  63332 non-null  int64
 11  TURNOVER (Rs.)      63332 non-null  float64
dtypes: float64(1), int64(3), object(8)
memory usage: 5.8+ MB

In [44]:
print("First 5 rows of df_2024:")
display(df_2024.head())
print("\nLast 5 rows of df_2024:")
display(df_2024.tail())

First 5 rows of df_2024:

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,AAF,N,0,ASIA ASSET,2024-01-04,12.00,12.00,12.00,12.00,3,1452,17424.0
1,AAF,N,0,ASIA ASSET,2024-01-05,12.50,12.00,12.50,12.00,4,23400,281550.0
2,AAF,N,0,ASIA ASSET,2024-01-09,12.00,12.00,12.00,12.00,4,20000,240000.0
3,AAF,N,0,ASIA ASSET,2024-01-12,12.50,12.00,12.00,12.00,2,111,1337.5
4,AAF,N,0,ASIA ASSET,2024-01-16,12.00,12.00,12.00,12.00,1,2000,24000.0

Last 5 rows of df_2024:

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
63327,YORK,N,0,YORK ARCADE,2024-12-24,158.50,153.00,155.50,153.25,29,2177,334672.25
63328,YORK,N,0,YORK ARCADE,2024-12-26,163.50,153.00,162.75,153.75,18,841,135673.75
63329,YORK,N,0,YORK ARCADE,2024-12-27,165.00,156.50,164.25,159.00,28,2897,474629.25
63330,YORK,N,0,YORK ARCADE,2024-12-30,172.00,160.00,162.50,165.00,31,2477,414664.00
63331,YORK,N,0,YORK ARCADE,2024-12-31,169.25,162.75,168.75,169.00,5,105,17721.25

In [48]:
import pandas as pd

file_path_2025 = '/content/2025 Data.xlsx'

# Load all sheets from the 2025 Data.xls file
# sheet_name=None returns a dictionary of DataFrames, one for each sheet
all_sheets_2025 = pd.read_excel(file_path_2025, sheet_name=None, header=3)

processed_dfs_2025 = []

for sheet_name, df_sheet in all_sheets_2025.items():
    # Ensure the sheet is not empty and contains enough rows for header processing
    if not df_sheet.empty and len(df_sheet) > 0:
        df_sheet_copy = df_sheet.copy()

        # Set the column names using the first row of the DataFrame (which contains the actual headers)
        # Make a copy to avoid SettingWithCopyWarning later
        df_sheet_copy.columns = df_sheet_copy.iloc[0]

        # Drop the first row as it has now become the header
        df_sheet_copy = df_sheet_copy[1:].reset_index(drop=True)

        # Clean column names by stripping whitespace
        df_sheet_copy.columns = df_sheet_copy.columns.str.strip()

        # Convert the 'TRADING DATE' column to datetime objects, coercing errors
        # Only attempt conversion if 'TRADING DATE' column exists
        if 'TRADING DATE' in df_sheet_copy.columns:
            df_sheet_copy['TRADING DATE'] = pd.to_datetime(df_sheet_copy['TRADING DATE'], errors='coerce')

            # Drop rows where 'TRADING DATE' is NaT (if any)
            df_sheet_copy.dropna(subset=['TRADING DATE'], inplace=True)

            # Convert the 'TRADING DATE' column to ISO 8601 (YYYY-MM-DD) string format
            df_sheet_copy['TRADING DATE'] = df_sheet_copy['TRADING DATE'].dt.strftime('%Y-%m-%d')
            processed_dfs_2025.append(df_sheet_copy)

# Concatenate all processed DataFrames into a single df_2025
df_2025 = pd.concat(processed_dfs_2025, ignore_index=True)

print(f"Processed file: {file_path_2025} from all sheets")
print("DataFrame after date conversion and concatenation:")
display(df_2025.head())
df_2025.info()

Processed file: /content/2025 Data.xlsx from all sheets
DataFrame after date conversion and concatenation:

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,AAF,N,0,ASIA ASSET,2025-01-02,27.2,26,26.9,26.9,32,27296,730958
1,AAF,N,0,ASIA ASSET,2025-01-03,27,26,26,26,43,219944,5751261.7
2,AAF,N,0,ASIA ASSET,2025-01-06,26,24,24.9,24.9,44,52830,1322547.5
3,AAF,N,0,ASIA ASSET,2025-01-07,28.4,26,28,28,577,1032138,28776826.7
4,AAF,N,0,ASIA ASSET,2025-01-08,28.5,27.9,28.2,28.2,213,439435,12470877.4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67541 entries, 0 to 67540
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   COMPANY ID          67541 non-null  object
 1   MAIN TYPE           67541 non-null  object
 2   SUB TYPE            67541 non-null  object
 3   SHORT NAME          67541 non-null  object
 4   TRADING DATE        67541 non-null  object
 5   PRICE HIGH (Rs.)    67539 non-null  object
 6   PRICE LOW (Rs.)     67541 non-null  object
 7   CLOSE PRICE (Rs.)   67541 non-null  object
 8   OPEN PRICE (Rs.)    67528 non-null  object
 9   TRADE VOLUME (No.)  67541 non-null  object
 10  SHARE VOLUME (No.)  67541 non-null  object
 11  TURNOVER (Rs.)      67541 non-null  object
dtypes: object(12)
memory usage: 6.2+ MB

In [49]:
print("First 5 rows of df_2025:")
display(df_2025.head())
print("\nLast 5 rows of df_2025:")
display(df_2025.tail())

First 5 rows of df_2025:

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,AAF,N,0,ASIA ASSET,2025-01-02,27.2,26,26.9,26.9,32,27296,730958
1,AAF,N,0,ASIA ASSET,2025-01-03,27,26,26,26,43,219944,5751261.7
2,AAF,N,0,ASIA ASSET,2025-01-06,26,24,24.9,24.9,44,52830,1322547.5
3,AAF,N,0,ASIA ASSET,2025-01-07,28.4,26,28,28,577,1032138,28776826.7
4,AAF,N,0,ASIA ASSET,2025-01-08,28.5,27.9,28.2,28.2,213,439435,12470877.4

Last 5 rows of df_2025:

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
67536,YORK,N,0,YORK ARCADE,2025-12-24,917.5,870,898.5,898.5,19,659,587417
67537,YORK,N,0,YORK ARCADE,2025-12-26,898.75,870,873.25,873.25,28,1548,1364836.75
67538,YORK,N,0,YORK ARCADE,2025-12-29,898,866,868.25,868.25,33,690,605430.5
67539,YORK,N,0,YORK ARCADE,2025-12-30,896.5,871,883.5,883.5,27,898,795450
67540,YORK,N,0,YORK ARCADE,2025-12-31,898,881,892.5,892.5,66,2183,1944432.25

In [50]:
# List of all annual DataFrames to merge
annual_dfs_to_merge = [
    df_2020,
    df_2021,
    df_2022,
    df_2023,
    df_2024,
    df_2025
]

# Concatenate all annual DataFrames into a single DataFrame
# Using ignore_index=True to reset the index of the combined DataFrame
combined_annual_df = pd.concat(annual_dfs_to_merge, ignore_index=True)

print("All annual dataframes have been merged into 'combined_annual_df'.")
print("First 5 rows of the combined DataFrame:")
display(combined_annual_df.head())
print("\nLast 5 rows of the combined DataFrame:")
display(combined_annual_df.tail())

combined_annual_df.info()

All annual dataframes have been merged into 'combined_annual_df'.
First 5 rows of the combined DataFrame:

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,AAF,N,0,ASIA ASSET,2020-01-02,8.80,8.50,8.60,8.80,7,522,4500.1
1,AAF,N,0,ASIA ASSET,2020-01-03,8.60,8.50,8.50,8.60,10,15582,132517.0
2,AAF,N,0,ASIA ASSET,2020-01-06,8.50,8.50,8.50,8.50,3,200,1700.0
3,AAF,N,0,ASIA ASSET,2020-01-07,8.40,8.30,8.30,8.40,6,700,5844.0
4,AAF,N,0,ASIA ASSET,2020-01-08,8.50,8.10,8.10,8.30,13,15926,129859.0

Last 5 rows of the combined DataFrame:

,COMPANY ID,MAIN TYPE,SUB TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
319114,YORK,N,0,YORK ARCADE,2025-12-24,917.5,870,898.5,898.5,19,659,587417
319115,YORK,N,0,YORK ARCADE,2025-12-26,898.75,870,873.25,873.25,28,1548,1364836.75
319116,YORK,N,0,YORK ARCADE,2025-12-29,898,866,868.25,868.25,33,690,605430.5
319117,YORK,N,0,YORK ARCADE,2025-12-30,896.5,871,883.5,883.5,27,898,795450
319118,YORK,N,0,YORK ARCADE,2025-12-31,898,881,892.5,892.5,66,2183,1944432.25

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319119 entries, 0 to 319118
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   COMPANY ID          319119 non-null  object
 1   MAIN TYPE           319119 non-null  object
 2   SUB TYPE            319119 non-null  object
 3   SHORT NAME          319119 non-null  object
 4   TRADING DATE        319119 non-null  object
 5   PRICE HIGH (Rs.)    319112 non-null  object
 6   PRICE LOW (Rs.)     319074 non-null  object
 7   CLOSE PRICE (Rs.)   319119 non-null  object
 8   OPEN PRICE (Rs.)    319081 non-null  object
 9   TRADE VOLUME (No.)  319119 non-null  object
 10  SHARE VOLUME (No.)  319119 non-null  object
 11  TURNOVER (Rs.)      319119 non-null  object
dtypes: object(12)
memory usage: 29.2+ MB

In [51]:
# Remove the 'SUB TYPE' column from the combined_annual_df
if 'SUB TYPE' in combined_annual_df.columns:
    combined_annual_df = combined_annual_df.drop(columns=['SUB TYPE'])
    print("Removed 'SUB TYPE' column from combined_annual_df.")
else:
    print("'SUB TYPE' column not found in combined_annual_df.")

print("\nFirst 5 rows of combined_annual_df after removing 'SUB TYPE':")
display(combined_annual_df.head())
combined_annual_df.info()

Removed 'SUB TYPE' column from combined_annual_df.

First 5 rows of combined_annual_df after removing 'SUB TYPE':

,COMPANY ID,MAIN TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,AAF,N,ASIA ASSET,2020-01-02,8.80,8.50,8.60,8.80,7,522,4500.1
1,AAF,N,ASIA ASSET,2020-01-03,8.60,8.50,8.50,8.60,10,15582,132517.0
2,AAF,N,ASIA ASSET,2020-01-06,8.50,8.50,8.50,8.50,3,200,1700.0
3,AAF,N,ASIA ASSET,2020-01-07,8.40,8.30,8.30,8.40,6,700,5844.0
4,AAF,N,ASIA ASSET,2020-01-08,8.50,8.10,8.10,8.30,13,15926,129859.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319119 entries, 0 to 319118
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   COMPANY ID          319119 non-null  object
 1   MAIN TYPE           319119 non-null  object
 2   SHORT NAME          319119 non-null  object
 3   TRADING DATE        319119 non-null  object
 4   PRICE HIGH (Rs.)    319112 non-null  object
 5   PRICE LOW (Rs.)     319074 non-null  object
 6   CLOSE PRICE (Rs.)   319119 non-null  object
 7   OPEN PRICE (Rs.)    319081 non-null  object
 8   TRADE VOLUME (No.)  319119 non-null  object
 9   SHARE VOLUME (No.)  319119 non-null  object
 10  TURNOVER (Rs.)      319119 non-null  object
dtypes: object(11)
memory usage: 26.8+ MB

In [52]:
combined_annual_df = combined_annual_df[combined_annual_df['MAIN TYPE'] == 'N']
print("Filtered combined_annual_df to include only 'MAIN TYPE' = 'N'.")
display(combined_annual_df.head())
combined_annual_df.info()

Filtered combined_annual_df to include only 'MAIN TYPE' = 'N'.

,COMPANY ID,MAIN TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,AAF,N,ASIA ASSET,2020-01-02,8.80,8.50,8.60,8.80,7,522,4500.1
1,AAF,N,ASIA ASSET,2020-01-03,8.60,8.50,8.50,8.60,10,15582,132517.0
2,AAF,N,ASIA ASSET,2020-01-06,8.50,8.50,8.50,8.50,3,200,1700.0
3,AAF,N,ASIA ASSET,2020-01-07,8.40,8.30,8.30,8.40,6,700,5844.0
4,AAF,N,ASIA ASSET,2020-01-08,8.50,8.10,8.10,8.30,13,15926,129859.0

<class 'pandas.core.frame.DataFrame'>
Index: 296403 entries, 0 to 319118
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   COMPANY ID          296403 non-null  object
 1   MAIN TYPE           296403 non-null  object
 2   SHORT NAME          296403 non-null  object
 3   TRADING DATE        296403 non-null  object
 4   PRICE HIGH (Rs.)    296396 non-null  object
 5   PRICE LOW (Rs.)     296358 non-null  object
 6   CLOSE PRICE (Rs.)   296403 non-null  object
 7   OPEN PRICE (Rs.)    296365 non-null  object
 8   TRADE VOLUME (No.)  296403 non-null  object
 9   SHARE VOLUME (No.)  296403 non-null  object
 10  TURNOVER (Rs.)      296403 non-null  object
dtypes: object(11)
memory usage: 27.1+ MB

In [53]:
company_ids_to_keep = ['ABL', 'CBNK', 'COMB', 'DFCC', 'HNB', 'HDFC', 'NDB', 'NTB', 'PABC', 'SAMP', 'SDB', 'SEYB', 'UBC']
combined_annual_df = combined_annual_df[combined_annual_df['COMPANY ID'].isin(company_ids_to_keep)]
print("Filtered combined_annual_df to include only specified 'COMPANY ID's.")
display(combined_annual_df.head())
combined_annual_df.info()

Filtered combined_annual_df to include only specified 'COMPANY ID's.

,COMPANY ID,MAIN TYPE,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
621,ABL,N,AMANA BANK,2020-01-02,2.40,2.30,2.30,2.30,51,331781,763510.9
622,ABL,N,AMANA BANK,2020-01-03,2.40,2.30,2.30,2.30,30,71444,164322.2
623,ABL,N,AMANA BANK,2020-01-06,2.40,2.20,2.30,2.30,25,61024,140379.6
624,ABL,N,AMANA BANK,2020-01-07,2.40,2.30,2.30,2.40,11,16219,37305.7
625,ABL,N,AMANA BANK,2020-01-08,2.30,2.20,2.20,2.30,20,156044,344820.5

<class 'pandas.core.frame.DataFrame'>
Index: 14927 entries, 621 to 316073
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   COMPANY ID          14927 non-null  object
 1   MAIN TYPE           14927 non-null  object
 2   SHORT NAME          14927 non-null  object
 3   TRADING DATE        14927 non-null  object
 4   PRICE HIGH (Rs.)    14927 non-null  object
 5   PRICE LOW (Rs.)     14907 non-null  object
 6   CLOSE PRICE (Rs.)   14927 non-null  object
 7   OPEN PRICE (Rs.)    14910 non-null  object
 8   TRADE VOLUME (No.)  14927 non-null  object
 9   SHARE VOLUME (No.)  14927 non-null  object
 10  TURNOVER (Rs.)      14927 non-null  object
dtypes: object(11)
memory usage: 1.4+ MB

In [2]:
output_combined_file_path = '/content/combined_annual_df.csv'
combined_annual_df.to_csv(output_combined_file_path, index=False)
print(f"Combined annual data saved to {output_combined_file_path}")

NameError: name 'combined_annual_df' is not defined

In [2]:
import pandas as pd

# Load the combined_annual_df from the saved CSV
combined_annual_df = pd.read_csv('/content/combined_annual_df.csv')

# 1. Drop the 'MAIN TYPE' column
if 'MAIN TYPE' in combined_annual_df.columns:
    combined_annual_df = combined_annual_df.drop(columns=['MAIN TYPE'])
    print("Dropped 'MAIN TYPE' column.")
else:
    print("'MAIN TYPE' column not found.")

# 2. Identify price and volume columns to clean and convert
columns_to_clean = [
    'PRICE HIGH (Rs.)',
    'PRICE LOW (Rs.)',
    'CLOSE PRICE (Rs.)',
    'OPEN PRICE (Rs.)',
    'TRADE VOLUME (No.)',
    'SHARE VOLUME (No.)',
    'TURNOVER (Rs.)'
]

# Clean and convert columns
for col in columns_to_clean:
    if col in combined_annual_df.columns:
        # Convert to string to handle various types before cleaning
        combined_annual_df[col] = combined_annual_df[col].astype(str)
        # Remove commas and any leading/trailing whitespace
        combined_annual_df[col] = combined_annual_df[col].str.replace(',', '', regex=False).str.strip()
        # Convert to numeric, coercing errors (e.g., '  -' or ' ' will become NaN)
        combined_annual_df[col] = pd.to_numeric(combined_annual_df[col], errors='coerce')
        print(f"Cleaned and converted '{col}' to numeric.")

# Display the first few rows and info of the updated DataFrame
print("\nDataFrame after cleaning and type conversion:")
display(combined_annual_df.head())
combined_annual_df.info()

Dropped 'MAIN TYPE' column.
Cleaned and converted 'PRICE HIGH (Rs.)' to numeric.
Cleaned and converted 'PRICE LOW (Rs.)' to numeric.
Cleaned and converted 'CLOSE PRICE (Rs.)' to numeric.
Cleaned and converted 'OPEN PRICE (Rs.)' to numeric.
Cleaned and converted 'TRADE VOLUME (No.)' to numeric.
Cleaned and converted 'SHARE VOLUME (No.)' to numeric.
Cleaned and converted 'TURNOVER (Rs.)' to numeric.

DataFrame after cleaning and type conversion:

,COMPANY ID,SHORT NAME,TRADING DATE,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,ABL,AMANA BANK,2020-01-02,2.4,2.3,2.3,2.3,51,331781,763510.9
1,ABL,AMANA BANK,2020-01-03,2.4,2.3,2.3,2.3,30,71444,164322.2
2,ABL,AMANA BANK,2020-01-06,2.4,2.2,2.3,2.3,25,61024,140379.6
3,ABL,AMANA BANK,2020-01-07,2.4,2.3,2.3,2.4,11,16219,37305.7
4,ABL,AMANA BANK,2020-01-08,2.3,2.2,2.2,2.3,20,156044,344820.5

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14927 entries, 0 to 14926
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   COMPANY ID          14927 non-null  object
 1   SHORT NAME          14927 non-null  object
 2   TRADING DATE        14927 non-null  object
 3   PRICE HIGH (Rs.)    14927 non-null  float64
 4   PRICE LOW (Rs.)     14893 non-null  float64
 5   CLOSE PRICE (Rs.)   14927 non-null  float64
 6   OPEN PRICE (Rs.)    14910 non-null  float64
 7   TRADE VOLUME (No.)  14927 non-null  int64
 8   SHARE VOLUME (No.)  14927 non-null  int64
 9   TURNOVER (Rs.)      14927 non-null  float64
dtypes: float64(5), int64(2), object(3)
memory usage: 1.1+ MB

In [3]:
# Check if 'TRADING DATE' exists and rename it to 'Date' for consistency
if 'TRADING DATE' in combined_annual_df.columns:
    combined_annual_df.rename(columns={'TRADING DATE': 'Date'}, inplace=True)
    print("Renamed 'TRADING DATE' to 'Date'.")

# 1. Parse 'Date' into datetime objects
# Using errors='coerce' will turn unparseable dates into NaT (Not a Time)
initial_rows_before_date_drop = combined_annual_df.shape[0]
combined_annual_df['Date'] = pd.to_datetime(combined_annual_df['Date'], errors='coerce')

# Drop rows where 'Date' could not be parsed (NaT values)
rows_dropped_due_to_date = combined_annual_df['Date'].isna().sum()
combined_annual_df.dropna(subset=['Date'], inplace=True)

if rows_dropped_due_to_date > 0:
    print(f"Dropped {rows_dropped_due_to_date} rows where 'Date' could not be parsed into a valid date.")
else:
    print("No rows were dropped due to unparseable 'Date' values.")

print("Converted 'Date' to datetime type.")

# 2. Sort by company and then by date
combined_annual_df.sort_values(by=['COMPANY ID', 'Date'], inplace=True)

print("Sorted DataFrame by 'COMPANY ID' and 'Date'.")

# 3. Remove duplicate (company, date) rows
initial_rows_before_duplicates = combined_annual_df.shape[0]
combined_annual_df.drop_duplicates(subset=['COMPANY ID', 'Date'], keep='first', inplace=True)
final_rows_after_duplicates = combined_annual_df.shape[0]

rows_dropped_due_to_duplicates = initial_rows_before_duplicates - final_rows_after_duplicates

if rows_dropped_due_to_duplicates > 0:
    print(f"Dropped {rows_dropped_due_to_duplicates} duplicate (company, date) rows. Kept the first occurrence.")
else:
    print("No duplicate (company, date) rows were found and dropped.")

# Display the first few rows, last few rows, and info of the updated DataFrame
print("\nDataFrame after date parsing, sorting, and duplicate removal:")
display(combined_annual_df.head())
display(combined_annual_df.tail())
combined_annual_df.info()

Renamed 'TRADING DATE' to 'Date'.
No rows were dropped due to unparseable 'Date' values.
Converted 'Date' to datetime type.
Sorted DataFrame by 'COMPANY ID' and 'Date'.
No duplicate (company, date) rows were found and dropped.

DataFrame after date parsing, sorting, and duplicate removal:

,COMPANY ID,SHORT NAME,Date,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,ABL,AMANA BANK,2020-01-02,2.4,2.3,2.3,2.3,51,331781,763510.9
1,ABL,AMANA BANK,2020-01-03,2.4,2.3,2.3,2.3,30,71444,164322.2
2,ABL,AMANA BANK,2020-01-06,2.4,2.2,2.3,2.3,25,61024,140379.6
3,ABL,AMANA BANK,2020-01-07,2.4,2.3,2.3,2.4,11,16219,37305.7
4,ABL,AMANA BANK,2020-01-08,2.3,2.2,2.2,2.3,20,156044,344820.5

,COMPANY ID,SHORT NAME,Date,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
14922,UBC,UNION BANK,2025-12-24,14.9,14.6,14.8,14.8,35,50365,748629.3
14923,UBC,UNION BANK,2025-12-26,15.0,14.6,14.7,14.7,28,77013,1141505.0
14924,UBC,UNION BANK,2025-12-29,14.9,14.5,14.7,14.7,31,133398,1956986.2
14925,UBC,UNION BANK,2025-12-30,15.0,14.5,14.9,14.9,41,24504,360107.5
14926,UBC,UNION BANK,2025-12-31,15.0,14.6,14.9,14.9,34,52858,787381.8

<class 'pandas.core.frame.DataFrame'>
Index: 14927 entries, 0 to 14926
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   COMPANY ID          14927 non-null  object
 1   SHORT NAME          14927 non-null  object
 2   Date                14927 non-null  datetime64[ns]
 3   PRICE HIGH (Rs.)    14927 non-null  float64
 4   PRICE LOW (Rs.)     14893 non-null  float64
 5   CLOSE PRICE (Rs.)   14927 non-null  float64
 6   OPEN PRICE (Rs.)    14910 non-null  float64
 7   TRADE VOLUME (No.)  14927 non-null  int64
 8   SHARE VOLUME (No.)  14927 non-null  int64
 9   TURNOVER (Rs.)      14927 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(2), object(2)
memory usage: 1.3+ MB

In [4]:
import numpy as np

# --- Adjust for known corporate actions (stock splits / share consolidations) ---
# These are NOT data errors — they're real, documented corporate actions that change
# the share basis without changing shareholder value. Left unadjusted, they show up
# as fake, extreme "returns" that will corrupt Daily_Return, Log_Return, MACD, RSI,
# ROC, and the 5-day-ahead target right around the event date.
#
# price_multiplier = factor to multiply PRE-event prices by, to bring them onto the
# POST-event share basis (i.e. adjust history to match today's share count).
#   > 1  -> a consolidation happened (fewer, higher-priced shares)
#   < 1  -> a split happened (more, lower-priced shares)
#
# Add more (company, effective_date, price_multiplier) rows here if you confirm
# additional corporate actions for the other banks later.
corporate_actions = [
    ('ABL',  '2024-07-15', 10.0),   # Amana Bank: 10 old shares consolidated into 1 new share
    ('SAMP', '2021-03-23', 1/3),    # Sampath Bank: 1 old share split into 3 new shares
]

price_cols  = ['OPEN PRICE (Rs.)', 'PRICE HIGH (Rs.)', 'PRICE LOW (Rs.)', 'CLOSE PRICE (Rs.)']
volume_cols = ['TRADE VOLUME (No.)', 'SHARE VOLUME (No.)']
# TURNOVER (Rs.) is deliberately left untouched — it's the actual Rs. value traded
# that day, which a split/consolidation does not change.

for company, effective_date, price_multiplier in corporate_actions:
    effective_date = pd.to_datetime(effective_date)
    mask = (combined_annual_df['COMPANY ID'] == company) & (combined_annual_df['Date'] < effective_date)

    combined_annual_df.loc[mask, price_cols]  = combined_annual_df.loc[mask, price_cols] * price_multiplier
    combined_annual_df.loc[mask, volume_cols] = combined_annual_df.loc[mask, volume_cols] / price_multiplier

    print(f"Adjusted {mask.sum()} pre-{effective_date.date()} rows for {company} "
          f"(prices x{price_multiplier:.4f}, volumes x{1/price_multiplier:.4f})")

Adjusted 855 pre-2024-07-15 rows for ABL (prices x10.0000, volumes x0.1000)
Adjusted 257 pre-2021-03-23 rows for SAMP (prices x0.3333, volumes x3.0000)

/tmp/ipykernel_683/151911791.py:31: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[5.100e+00 3.000e+00 2.500e+00 1.100e+00 2.000e+00 1.300e+00 6.700e+00
 2.100e+00 3.100e+00 1.800e+00 1.300e+00 9.000e-01 2.700e+00 1.700e+00
 1.500e+00 9.000e-01 7.000e-01 5.000e-01 3.000e-01 1.000e+00 2.100e+00
 1.400e+00 8.000e-01 9.000e-01 5.300e+00 1.000e+00 7.000e-01 6.000e-01
 3.000e+00 4.000e-01 1.300e+00 2.500e+00 2.000e-01 1.900e+00 7.000e-01
 4.000e-01 7.000e-01 1.600e+00 1.800e+00 5.000e-01 1.600e+00 1.100e+00
 1.700e+00 3.700e+00 1.100e+00 1.500e+00 3.100e+00 2.000e+00 3.000e-01
 1.900e+00 1.600e+00 7.000e-01 1.000e+00 1.400e+00 4.000e-01 2.000e+00
 2.500e+00 8.000e-01 7.000e-01 1.800e+00 2.400e+00 1.700e+00 1.000e+00
 3.800e+00 5.000e-01 1.000e-01 8.000e-01 3.500e+00 1.200e+00 1.600e+00
 2.000e+00 2.000e+00 2.000e-01 1.800e+00 4.000e+00 1.900e+00 6.000e-01
 4.000e-01 9.000e-01 1.300e+00 7.000e-01 4.600e+00 9.000e-01 9.000e-01
 4.800e+00 1.700e+00 2.000e-01 2.300e+00 2.000e+00 1.400e+00 1.700e+00
 2.900e+00 9.000e-01 1.000e+00 7.000e-01 8.000e-01 1.300e+00 1.400e+00
 7.000e-01 1.700e+00 2.300e+00 2.800e+00 5.400e+00 1.300e+00 2.000e+00
 1.500e+00 1.100e+00 5.000e-01 1.500e+00 1.200e+00 1.000e-01 1.200e+00
 4.000e-01 8.000e-01 4.000e-01 4.000e-01 1.500e+00 9.000e-01 3.100e+00
 1.000e+00 7.000e-01 1.000e+00 4.000e-01 2.100e+00 3.000e-01 1.600e+00
 1.200e+00 7.000e-01 9.000e-01 2.900e+00 2.100e+00 4.300e+00 1.400e+00
 2.430e+01 1.780e+01 5.900e+00 5.200e+00 5.400e+00 6.900e+00 3.300e+00
 2.500e+00 2.700e+00 3.600e+00 1.900e+00 3.000e+00 5.400e+00 3.850e+01
 1.390e+01 1.350e+01 9.600e+00 2.800e+00 3.900e+00 2.460e+01 1.240e+01
 3.040e+01 1.360e+01 1.200e+01 3.700e+00 4.500e+00 2.300e+00 7.600e+00
 4.000e+00 1.500e+00 4.500e+00 2.900e+00 2.500e+00 4.400e+00 1.800e+00
 5.300e+00 4.300e+00 4.600e+00 6.700e+00 3.400e+00 2.300e+00 3.800e+00
 1.400e+00 1.500e+00 2.900e+00 1.800e+00 3.100e+00 1.100e+00 1.400e+00
 3.900e+00 2.600e+00 1.110e+01 4.600e+00 4.800e+00 8.000e+00 4.890e+01
 1.020e+01 3.800e+00 7.600e+00 8.400e+00 5.200e+00 3.700e+00 9.200e+00
 2.300e+00 9.200e+00 5.800e+00 1.570e+01 6.100e+00 2.300e+00 4.400e+00
 4.000e+00 1.700e+00 3.400e+00 5.200e+00 3.700e+00 2.400e+00 6.500e+00
 2.700e+00 5.700e+00 2.600e+00 1.870e+01 8.800e+00 4.600e+00 5.900e+00
 3.700e+00 1.030e+01 1.229e+02 4.010e+01 4.490e+01 3.160e+01 8.030e+01
 3.220e+01 1.800e+01 1.070e+01 1.150e+01 1.440e+01 1.340e+01 9.000e+00
 2.700e+00 1.060e+01 9.400e+00 1.140e+01 8.300e+00 7.300e+00 6.400e+00
 5.300e+00 5.000e+00 2.700e+00 4.600e+00 8.100e+00 2.600e+00 4.500e+00
 3.500e+00 6.300e+00 3.800e+00 4.900e+00 2.100e+00 3.200e+00 2.900e+00
 2.300e+00 1.800e+00 3.300e+00 6.300e+00 2.500e+00 4.100e+00 5.000e+00
 1.800e+00 1.400e+00 4.300e+00 3.400e+00 2.100e+00 4.000e-01 3.300e+00
 2.600e+00 3.100e+00 3.000e+00 3.700e+00 4.300e+00 3.300e+00 5.800e+00
 1.030e+01 5.200e+00 3.400e+00 1.200e+00 4.900e+00 2.400e+00 2.000e+00
 2.200e+00 8.000e+00 8.200e+00 6.300e+00 3.600e+00 4.000e+00 2.900e+00
 1.800e+00 1.000e+00 3.000e+00 9.000e-01 6.000e-01 3.500e+00 2.400e+00
 3.500e+00 2.700e+00 1.200e+00 1.400e+00 2.900e+00 1.800e+00 4.300e+00
 3.800e+00 5.000e+00 1.900e+00 1.300e+00 3.300e+00 3.900e+00 2.100e+00
 1.900e+00 1.100e+00 6.700e+00 2.800e+00 2.600e+00 2.400e+00 1.800e+00
 6.900e+00 7.000e-01 7.000e-01 8.000e-01 4.600e+00 4.900e+00 1.600e+00
 1.100e+00 2.300e+00 5.500e+00 5.600e+00 9.200e+00 1.383e+02 2.472e+02
 8.100e+01 2.330e+01 1.270e+01 2.330e+01 1.040e+01 2.720e+01 1.830e+01
 1.790e+01 1.750e+01 1.220e+01 1.570e+01 1.820e+01 9.340e+01 2.700e+01
 3.600e+01 1.920e+01 1.610e+01 1.080e+01 9.300e+00 1.350e+01 5.800e+00
 6.000e+00 8.500e+00 1.580e+01 1.650e+01 1.051e+02 2.250e+01 1.200e+01
 1.820e+01 9.800e+00 2.060e+01 1.950e+01 7.300e+00 1.110e+01 2.140e+01
 8.600e+00 6.200e+00 5.300e+00 7.000e+00 6.100e+00 4.300e+00 4.200e+00
 9.300e+00 8.100e+00 1.260e+01 7.460e+01 4.100e+01 1.070e+01 1.700e+01
 9.500e+00 1.180e+01 7.800e+00 9.300e+00 5.300e+00 7.100e+00 1.130e+01
 6.500e+00 8.800e+00 4.110e+01 1.800e+01 2.060e+01 7.080e+01 2.342e+02
 4.450e+01 3.500e+01 1.530e+01 1.470e+01 9.300e+00 2.380e+01 1.440e+01
 2.250e+01 1.160e+01 1.010e+01 1.500e+01 9.900e+00 1.080e+01 7.400e+00
 1.430e+01 1.520e+01 1.410e+01 2.430e+01 1.450e+01 9.100e+00 8.000e+00
 3.200e+00 8.000e+00 9.400e+00 1.060e+01 1.140e+01 1.810e+01 1.790e+01
 1.720e+01 1.490e+01 1.880e+01 4.300e+00 6.500e+00 6.600e+00 9.400e+00
 1.330e+01 2.110e+01 9.100e+00 5.300e+00 5.000e+00 1.310e+01 4.900e+00
 3.100e+00 3.500e+00 5.700e+00 6.100e+00 6.100e+00 4.400e+00 1.700e+00
 1.190e+01 1.490e+01 5.200e+00 1.800e+00 9.400e+00 4.900e+00 4.600e+00
 7.400e+00 4.200e+00 1.500e+00 2.800e+00 5.200e+00 1.170e+01 1.270e+01
 6.000e+00 3.700e+00 5.100e+00 5.300e+00 7.600e+00 1.150e+01 1.080e+01
 1.450e+01 5.000e+00 2.700e+00 5.600e+00 3.100e+00 1.600e+01 9.500e+00
 2.180e+01 1.200e+01 8.800e+00 8.400e+00 4.300e+00 2.300e+00 7.900e+00
 8.000e+00 2.700e+00 3.700e+00 3.700e+00 1.800e+00 2.100e+00 2.400e+00
 5.800e+00 3.200e+00 2.200e+00 4.600e+00 1.500e+00 3.400e+00 6.600e+00
 4.300e+00 1.700e+00 5.300e+00 2.900e+00 3.300e+00 1.700e+00 1.100e+00
 2.700e+00 2.100e+00 1.400e+00 1.500e+01 2.200e+00 1.000e+00 4.000e+00
 2.200e+00 1.690e+01 6.000e+00 1.800e+01 1.950e+01 5.000e+00 5.800e+00
 9.300e+00 1.070e+01 7.900e+00 4.490e+01 1.760e+01 1.110e+01 4.200e+00
 4.400e+00 3.400e+00 3.800e+00 7.600e+00 1.590e+01 2.320e+01 2.920e+01
 2.110e+01 3.670e+01 1.410e+01 1.830e+01 1.940e+01 1.180e+01 1.000e+01
 1.790e+01 1.800e+01 2.430e+01 2.280e+01 3.150e+01 1.960e+01 8.000e+00
 5.700e+00 5.900e+00 1.540e+01 2.060e+01 1.700e+01 1.540e+01 8.100e+00
 1.170e+01 6.400e+00 9.700e+00 3.800e+00 9.200e+00 5.000e+00 7.700e+00
 5.500e+00 9.900e+00 8.100e+00 5.300e+00 3.000e+00 1.060e+01 4.300e+00
 4.800e+00 2.600e+00 7.500e+00 8.200e+00 5.400e+00 4.000e+00 5.800e+00
 2.600e+00 4.300e+00 5.200e+00 1.040e+01 5.600e+00 8.700e+00 2.500e+00
 1.800e+00 3.100e+00 4.300e+00 2.200e+00 2.500e+00 7.900e+00 9.400e+00
 6.800e+00 2.600e+00 3.000e+00 6.300e+00 2.700e+00 6.200e+00 2.800e+00
 1.500e+00 7.500e+00 6.100e+00 3.800e+00 3.200e+00 5.200e+00 2.900e+00
 1.300e+00 2.600e+00 2.200e+00 3.100e+00 5.200e+00 1.090e+01 7.700e+00
 8.400e+00 4.500e+00 4.400e+00 1.040e+01 1.130e+01 5.000e+00 8.800e+00
 3.120e+01 1.000e+01 8.500e+00 6.330e+01 1.610e+01 9.600e+00 1.290e+01
 1.210e+01 6.700e+00 7.700e+00 2.550e+01 3.380e+01 2.420e+01 1.960e+01
 1.330e+01 1.750e+01 1.120e+01 1.530e+01 1.390e+01 4.000e+00 1.260e+01
 9.100e+00 5.200e+00 8.600e+00 1.520e+01 6.400e+00 6.300e+00 4.900e+00
 1.510e+01 4.500e+00 2.300e+00 4.400e+00 5.300e+00 3.300e+00 5.700e+00
 7.600e+00 2.420e+01 6.500e+00 1.430e+01 8.100e+00 6.200e+00 6.200e+00
 1.060e+01 5.500e+00 5.600e+00 5.100e+00 4.100e+00 3.500e+00 6.100e+00
 2.700e+00 2.300e+00 6.600e+00 4.200e+00 6.700e+00 1.100e+00 6.200e+00
 2.200e+00 2.800e+00 1.400e+00 4.100e+00 1.500e+00 1.200e+00 3.700e+00
 6.200e+00 3.300e+00 1.200e+00 7.000e-01 5.400e+00 8.600e+00 3.900e+00
 3.700e+00 2.600e+00 2.000e+00 2.800e+00 2.300e+00 1.500e+00 1.600e+00
 9.500e+00 2.000e+00 3.100e+00 4.100e+00 7.100e+00 3.300e+00 2.100e+00
 8.600e+00 3.300e+00 1.500e+00 3.200e+00 1.500e+00 2.100e+00 3.100e+00
 2.700e+00 1.800e+00 1.200e+00 4.800e+00 1.800e+00 3.000e+00 1.900e+00
 1.400e+00 1.100e+00 2.700e+00 4.000e+00 2.000e+00 9.100e+00 2.800e+00
 1.900e+00 2.000e+00 1.100e+00 7.400e+00 1.280e+01 4.700e+00 1.000e+00
 2.100e+00 2.900e+00 2.700e+00 9.000e-01 1.800e+00 4.800e+00 1.000e+00
 2.000e+00 2.900e+00 1.100e+00 9.000e-01 3.600e+00 3.800e+00 1.400e+00
 2.700e+00 3.900e+00 1.700e+00 3.500e+00 1.200e+00 1.600e+00 1.000e+00
 1.300e+00 8.000e-01 1.700e+00 5.700e+00 6.000e-01 3.400e+00 1.000e+00
 1.700e+00 5.100e+00 2.000e+00 2.400e+00 3.300e+00 1.500e+00 4.000e-01
 9.000e-01 1.600e+00 2.300e+00 1.500e+00 1.200e+00 3.400e+00 1.200e+00
 1.700e+00 3.300e+00 1.000e+00 1.600e+00 9.000e-01 2.900e+00 1.900e+00
 9.000e-01 3.500e+00 3.200e+00 1.300e+00 2.800e+00 3.600e+00 3.500e+00
 2.100e+00 2.540e+01 3.060e+01 5.500e+00 3.700e+00 1.300e+01 4.300e+00
 4.500e+00 4.400e+00 2.100e+00 4.000e+00 4.100e+00 3.100e+00 2.900e+00
 3.500e+00 6.800e+00 2.600e+00 5.600e+00 2.000e+00 1.040e+01 1.530e+01
 5.500e+00 7.600e+00 1.280e+01 1.270e+01 5.800e+00 3.500e+00 3.200e+00
 1.080e+01 2.020e+01 4.320e+01 2.620e+01 5.500e+00 3.600e+00 5.800e+00
 4.700e+00 4.800e+00 1.190e+01 1.200e+01 3.700e+00 1.310e+01 1.730e+01
 7.100e+00 3.500e+00 5.400e+00 1.900e+00 1.500e+00 6.900e+00 1.800e+00
 1.400e+00 2.600e+00 2.600e+00 1.170e+01 5.300e+00 1.280e+01 1.000e+01
 5.700e+00 6.500e+00 3.000e+00 1.000e+00 2.000e+00 1.800e+00 3.400e+00
 1.400e+00 2.200e+00 1.200e+00 2.600e+00 1.260e+01 5.400e+00 6.200e+00
 3.000e+00 2.200e+00 2.900e+00 1.700e+00 2.300e+00 3.500e+00 3.600e+00
 3.300e+00]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  combined_annual_df.loc[mask, volume_cols] = combined_annual_df.loc[mask, volume_cols] / price_multiplier
/tmp/ipykernel_683/151911791.py:31: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[3.31781000e+04 7.14440000e+03 6.10240000e+03 1.62190000e+03
 1.56044000e+04 1.52641000e+04 1.63313490e+06 2.88679000e+04
 1.91740000e+04 2.48935000e+04 1.30549000e+04 3.02521000e+04
 4.87860000e+04 4.01868000e+04 5.07983000e+04 1.70400000e+04
 2.77900000e+02 2.14300000e+02 5.18000000e+01 2.56260000e+03
 7.25000000e+03 1.46910000e+04 8.15550000e+03 2.22330000e+03
 6.63180000e+04 5.33410000e+04 2.45630000e+03 3.06400000e+02
 3.74060000e+04 1.20000000e+03 6.26120000e+03 4.03619000e+04
 1.62000000e+01 3.42378000e+04 8.43080000e+03 6.29000000e+03
 4.04410000e+03 2.99675000e+04 3.91490000e+03 6.09700000e+02
 2.02935000e+04 6.00400000e+02 1.70438000e+04 1.56955000e+04
 5.15050000e+03 3.20520000e+03 1.45957000e+04 6.75100000e+03
 1.10000000e+03 5.83650200e+05 1.99700000e+03 1.43700000e+02
 8.01100000e+02 6.26220000e+03 1.28000000e+02 2.06289000e+04
 9.30500000e+03 2.66070000e+03 2.95000000e+03 7.43940000e+03
 3.89336000e+04 2.40834000e+04 1.00603000e+04 1.71404000e+04
 2.69150000e+03 4.00000000e+03 9.13600000e+02 4.74152000e+04
 6.08100000e+03 8.08960000e+03 1.04079000e+04 8.58090000e+03
 5.20000000e+00 1.16744000e+04 8.30426600e+05 1.26895000e+04
 1.69000000e+03 3.71000000e+03 3.25640000e+03 8.02110000e+03
 1.61490000e+03 3.29616000e+04 5.28800000e+03 2.06799000e+04
 4.32124000e+04 1.16000000e+04 1.10000000e+01 3.52350000e+03
 5.11200000e+04 1.60010000e+04 1.18213000e+04 2.83316000e+04
 2.02300000e+02 3.26000000e+02 8.02700000e+02 4.17700000e+02
 7.32760000e+03 2.85050000e+03 1.01800000e+04 1.01365310e+06
 6.26852000e+04 2.47932000e+04 6.03325000e+04 2.69200000e+04
 1.76315000e+04 5.40200000e+02 1.57340000e+03 2.12520000e+03
 1.03511000e+04 2.15500000e+03 6.30000000e+00 1.63380000e+03
 5.64500000e+02 3.80000000e+02 4.81000000e+02 5.59500000e+02
 2.93507000e+04 2.26510000e+03 1.76124000e+04 1.60800000e+03
 2.13200000e+03 1.18010000e+03 4.10000000e+02 6.89000000e+03
 5.88000000e+02 2.08180000e+04 2.60400000e+03 1.94860000e+03
 1.84800000e+03 2.26829600e+05 1.60686000e+04 3.46187000e+04
 9.28200000e+03 2.22909600e+05 7.12934000e+04 3.12271000e+04
 1.86800000e+04 4.27682000e+04 6.75497000e+04 7.98240000e+03
 2.30205000e+04 1.56499000e+04 2.50434000e+04 1.61910000e+04
 2.70144000e+04 2.71790000e+04 5.85141200e+05 1.44967000e+05
 8.05566000e+04 5.91058000e+04 2.69957000e+04 3.96613000e+04
 2.11334000e+05 2.51115200e+05 8.77127600e+05 1.77427800e+05
 6.74718400e+05 1.93005000e+04 3.15163000e+05 3.31360000e+03
 1.14628400e+05 2.02141000e+04 2.33930000e+03 2.30923000e+04
 4.84864000e+04 1.25312000e+04 3.29991000e+04 2.62053000e+04
 3.69712000e+04 1.52547000e+04 6.62360000e+04 2.22406700e+05
 2.09204000e+04 3.07282000e+04 2.27267000e+04 7.54880000e+03
 2.37650000e+03 6.99740000e+03 3.88500000e+03 3.78040000e+03
 5.22520000e+03 2.44240000e+03 1.31559000e+04 1.88095000e+04
 7.58740000e+04 5.82365000e+04 2.80820000e+03 3.09247500e+05
 4.41610100e+05 6.52079000e+04 1.65166000e+04 7.44877000e+04
 9.60133000e+04 6.33746000e+04 3.01423000e+04 1.15663900e+05
 1.13852000e+04 7.81677000e+04 2.52837000e+04 2.10191900e+05
 3.62053000e+04 1.93530000e+03 1.21533000e+04 1.61536000e+04
 3.99500000e+02 2.98262000e+04 1.27825000e+04 8.50925000e+04
 1.59279000e+04 2.10999000e+04 2.37381000e+04 3.65973000e+04
 6.14158000e+04 2.18999200e+05 1.37085500e+05 2.75871000e+04
 5.06303000e+04 3.46206000e+04 1.83898100e+05 2.50420720e+06
 4.58174100e+05 6.14708400e+05 4.33051800e+05 2.28135750e+06
 3.43896100e+05 2.48410900e+05 7.30374000e+04 1.32356100e+05
 2.16096300e+05 1.00003700e+05 5.58725000e+04 1.68558000e+04
 1.47145400e+05 5.95508000e+04 7.48925000e+04 6.43026000e+04
 5.35235000e+04 3.65909000e+04 1.16556000e+05 5.92828000e+04
 9.07270000e+03 1.13109000e+04 5.80907000e+04 3.98618000e+04
 5.23297000e+04 2.58601000e+04 2.81745000e+04 1.65095000e+04
 4.38073000e+04 1.10102000e+04 7.48450000e+03 1.29880000e+04
 1.35369000e+04 6.97320000e+03 1.40368000e+04 8.59737000e+04
 8.04100000e+04 1.07888800e+05 7.33187000e+04 5.34240000e+03
 5.29100000e+04 2.74109000e+04 1.91530000e+04 6.12011000e+04
 1.40500000e+02 1.85324000e+04 8.60201000e+04 5.89502000e+04
 2.38008000e+04 1.77312000e+04 2.66729000e+04 3.40232000e+04
 4.59996000e+04 1.35610200e+05 3.12388000e+04 1.76020000e+04
 7.85755000e+04 4.68712000e+04 4.95560000e+03 9.78130000e+03
 5.26900000e+03 1.48524500e+05 3.86969000e+04 9.32408000e+04
 3.13687000e+04 3.37850000e+04 1.22781000e+04 9.11830000e+03
 6.53400000e+02 1.29700000e+04 1.71530000e+03 5.18000000e+02
 1.30874000e+04 2.52546000e+04 2.42721000e+04 6.24380000e+03
 2.10890000e+03 1.96120000e+03 1.79601000e+04 2.50080000e+03
 8.68040000e+04 1.14740000e+04 6.19640000e+04 6.49510000e+03
 4.87460000e+03 2.91539000e+04 7.79193000e+04 1.32605000e+04
 3.23090000e+03 5.70430000e+03 2.14777000e+04 7.35420000e+03
 1.31427000e+04 2.69152000e+04 8.38180000e+03 4.50150000e+04
 3.51900000e+02 5.30500000e+02 3.31870000e+03 5.08176000e+04
 1.54108000e+04 8.90140000e+03 3.94060000e+03 1.51551000e+04
 2.39574000e+04 2.23977000e+04 3.91114000e+04 4.20225950e+06
 3.37438120e+06 1.81494930e+06 2.76538100e+05 1.50821400e+05
 2.52979400e+05 1.02806000e+05 9.34115000e+04 1.61057000e+05
 1.27936000e+05 1.17825700e+05 8.36880000e+05 2.18776200e+05
 1.63172000e+05 1.81628340e+06 2.57650700e+05 4.32209700e+05
 4.16839200e+05 2.52507700e+05 1.45419700e+05 5.71768000e+04
 1.33566600e+05 6.03137000e+04 1.15682200e+05 1.16237000e+05
 1.95257500e+05 1.72624400e+05 1.49125090e+06 2.55281700e+05
 8.36371000e+04 1.35775100e+05 7.54192000e+04 2.22901400e+05
 1.33087900e+05 7.84594000e+04 1.46337200e+05 4.94532100e+05
 7.27600000e+04 4.18822000e+04 3.71472000e+04 4.07322000e+04
 8.38682000e+04 3.14392000e+04 2.98182000e+04 5.15735000e+04
 6.59733000e+04 1.44728500e+05 2.01065860e+06 1.07867690e+06
 3.74563200e+05 1.58025100e+05 3.08730000e+04 7.36403000e+04
 3.06235900e+05 8.50297300e+05 2.04723130e+06 8.88454000e+04
 9.08726000e+04 4.30282000e+04 1.34896400e+05 5.17396900e+05
 1.21189500e+05 1.28669800e+05 2.23919858e+07 3.61632320e+06
 4.65477800e+05 2.64364600e+05 1.04558800e+05 1.33840300e+05
 6.45987000e+04 2.20291900e+05 1.44996500e+05 1.68263900e+05
 3.32538000e+04 1.08551200e+05 1.59658600e+05 4.29034000e+04
 4.38351000e+04 4.35538000e+04 6.65665000e+04 1.08777400e+05
 7.70716000e+04 2.69206600e+05 1.10696300e+05 5.07141000e+04
 4.10513000e+04 4.78570000e+03 3.17555000e+04 6.76137000e+04
 3.95773000e+04 4.95542000e+04 9.50147000e+04 8.44956000e+04
 1.66257700e+05 1.06555200e+05 1.60379400e+05 2.68279000e+04
 1.75521000e+04 2.73244000e+04 7.98219000e+04 8.14473000e+04
 2.72498700e+05 6.92982000e+04 1.76120000e+04 1.23263000e+04
 1.13905800e+05 3.41427000e+04 1.50007000e+04 1.34413000e+04
 7.82776000e+04 6.18147000e+04 1.26976900e+05 2.44178000e+04
 8.71540000e+03 1.85131300e+05 1.11317100e+05 1.15177000e+04
 4.28730000e+03 3.43593000e+04 3.72584000e+04 6.13440000e+03
 3.79055000e+04 1.49979000e+04 8.08220000e+03 1.94791000e+04
 1.37296200e+05 1.54166000e+05 1.31604800e+05 3.21833000e+04
 1.27860000e+04 3.36570000e+04 2.52378000e+04 4.66341000e+04
 1.14309400e+05 6.27107000e+04 1.18926600e+05 3.45366000e+04
 4.22420000e+03 1.21873800e+05 4.20086000e+04 2.69084300e+05
 2.92052100e+05 2.72579800e+05 1.14813300e+05 1.41599100e+05
 2.17971700e+05 2.76716000e+04 2.83826000e+04 6.84156000e+04
 8.33981000e+04 9.11550000e+03 1.63894000e+04 2.02578000e+04
 3.26971000e+04 2.44370000e+03 1.78654000e+04 4.58581000e+04
 3.53661000e+04 1.07286000e+04 4.43165000e+04 8.17280000e+03
 8.07619000e+04 5.23269000e+04 1.72446000e+04 3.63490000e+03
 6.07737000e+04 8.54010000e+03 7.37600000e+03 2.10870000e+04
 1.56370000e+03 9.85940000e+03 5.52096000e+04 3.48720000e+03
 1.12561667e+07 3.41877000e+04 7.80510000e+03 7.61373000e+04
 3.64620000e+03 2.94039000e+05 2.29650000e+04 3.08379400e+05
 1.35676500e+05 3.98071000e+04 4.18539000e+04 1.67192100e+05
 1.85723700e+05 1.33634400e+05 6.60427300e+05 2.13289000e+05
 1.60529600e+05 3.05611000e+04 6.07742000e+04 4.73974000e+04
 6.67136000e+04 1.14607200e+05 2.35319400e+05 3.51129600e+05
 3.14740100e+05 5.83156500e+05 8.78183500e+05 1.59259000e+05
 3.29478700e+05 2.74020900e+05 1.13772500e+05 7.74257000e+04
 2.98765200e+05 3.48664700e+05 5.27548100e+05 3.15071900e+05
 6.42236000e+05 3.75733600e+05 8.38890000e+04 4.54398000e+04
 3.94502000e+04 2.36075100e+05 2.86139700e+05 3.20695000e+05
 2.10449700e+05 7.14575000e+04 2.48894000e+05 4.27898000e+04
 1.18793200e+05 1.37547000e+04 1.22365600e+05 1.62669000e+04
 3.99423000e+04 5.01101000e+04 5.01051000e+04 3.30802000e+04
 6.44887000e+04 3.21488000e+04 1.45874500e+05 9.88150000e+03
 5.06321000e+04 1.51315000e+04 4.83785000e+04 3.58065000e+04
 2.49496000e+04 9.73070000e+03 2.36848000e+04 3.68000000e+04
 8.76760000e+03 5.79312000e+04 1.11111200e+05 5.69320000e+04
 5.45417000e+04 2.05172000e+04 1.81800000e+03 8.63110000e+03
 1.55761000e+04 6.05700000e+03 1.04955000e+04 5.10773000e+04
 1.09817200e+05 6.59995000e+04 8.79110000e+03 2.85045000e+04
 3.28323000e+04 8.52320000e+03 4.28740000e+04 8.07130000e+03
 6.84460000e+03 4.51994000e+04 9.83874000e+04 4.26979000e+04
 2.10416000e+04 3.29721000e+04 3.71370000e+03 1.62710000e+03
 8.56050000e+03 1.77420000e+04 6.88860000e+04 2.24831000e+04
 2.01716900e+05 7.93425000e+04 7.93905000e+04 4.15112000e+04
 4.59787000e+04 6.13701000e+04 1.87488100e+05 1.34215000e+04
 1.77836500e+05 7.93432100e+05 6.13684300e+05 2.19049500e+05
 1.22964930e+06 2.01994900e+05 9.65226000e+04 1.56275900e+05
 1.88456200e+05 5.27152000e+04 3.38651000e+04 2.21072600e+05
 7.18180200e+05 3.14117500e+05 1.50690000e+05 1.37662800e+05
 1.64314200e+05 1.61865300e+05 1.59041100e+05 1.83085400e+05
 9.54160000e+03 1.42202300e+05 1.90547600e+05 3.77455000e+04
 4.55092000e+04 1.27100000e+05 5.63860000e+04 6.20979000e+04
 3.08443000e+04 3.58499100e+05 1.26379700e+05 9.29070000e+03
 6.98135000e+04 6.24404000e+04 6.29173000e+04 9.32477000e+04
 2.12745700e+05 7.22537300e+05 4.89507000e+04 2.58146900e+05
 6.71500000e+04 2.30766000e+04 9.49750000e+03 1.72126500e+05
 2.16501000e+04 2.05229000e+04 3.73516000e+04 4.30957000e+04
 7.69090000e+04 1.07671600e+05 1.42463000e+04 1.76873000e+04
 1.34731000e+05 7.66574000e+04 5.32007000e+04 7.23500000e+02
 2.40987000e+04 2.54600000e+03 5.09250000e+03 5.64070000e+03
 3.73515000e+04 1.08877000e+04 6.98160000e+03 3.86649000e+04
 5.58586000e+04 2.34208000e+04 5.70200000e+02 4.05710000e+03
 5.61517000e+04 1.27427700e+05 1.27850000e+04 3.01421000e+04
 1.18926000e+04 6.11400000e+02 4.96429000e+04 6.28980000e+03
 5.14910000e+03 1.17760000e+04 1.30444200e+05 4.12280000e+03
 3.67934000e+04 5.88178000e+04 1.37849900e+05 6.61610000e+03
 5.11110000e+03 1.47044000e+05 6.46340000e+03 2.09580000e+03
 8.11397000e+04 2.98890000e+03 5.04730000e+03 1.58460000e+04
 9.93830000e+03 2.52020000e+03 1.38740000e+03 1.99863000e+04
 1.62494000e+04 3.12984000e+04 1.74580000e+03 1.96020000e+03

In [5]:
check = combined_annual_df.sort_values(['COMPANY ID','Date']).copy()
check['ret_check'] = check.groupby('COMPANY ID')['CLOSE PRICE (Rs.)'].pct_change()
remaining = check[check['ret_check'].abs() > 0.4][['COMPANY ID','Date','CLOSE PRICE (Rs.)','ret_check']]
print("Remaining extreme single-day moves (>40%) after adjustment:")
display(remaining)

Remaining extreme single-day moves (>40%) after adjustment:

Empty DataFrame
Columns: [COMPANY ID, Date, CLOSE PRICE (Rs.), ret_check]
Index: []

In [6]:
import numpy as np

# Ensure 'Date' is datetime type for proper sorting and shifting
# (It should already be from the previous step, but good to ensure)
combined_annual_df['Date'] = pd.to_datetime(combined_annual_df['Date'])

# Sort by company and then by date to ensure correct 'previous day' logic
combined_annual_df.sort_values(by=['COMPANY ID', 'Date'], inplace=True)

# --- Handle missing 'OPEN PRICE (Rs.)' ---
initial_missing_open = combined_annual_df['OPEN PRICE (Rs.)'].isnull().sum()

# Calculate previous day's close price within each company group
combined_annual_df['PREV_CLOSE'] = combined_annual_df.groupby('COMPANY ID')['CLOSE PRICE (Rs.)'].shift(1)

# Fill missing 'OPEN PRICE (Rs.)' with 'PREV_CLOSE'
combined_annual_df['OPEN PRICE (Rs.)'] = combined_annual_df['OPEN PRICE (Rs.)'].fillna(combined_annual_df['PREV_CLOSE'])

# Drop the temporary 'PREV_CLOSE' column
combined_annual_df.drop(columns=['PREV_CLOSE'], inplace=True)

filled_open_count = initial_missing_open - combined_annual_df['OPEN PRICE (Rs.)'].isnull().sum()
print(f"Filled {filled_open_count} missing 'OPEN PRICE (Rs.)' values with previous day's close.")

# --- Handle missing 'PRICE LOW (Rs.)' ---
initial_missing_low = combined_annual_df['PRICE LOW (Rs.)'].isnull().sum()

# Fill missing 'PRICE LOW (Rs.)' with the minimum of 'OPEN PRICE (Rs.)' and 'CLOSE PRICE (Rs.)'
# It's important that 'OPEN PRICE (Rs.)' has already been partially imputed here.
# Use np.fmin for element-wise minimum, handling potential NaN values gracefully
combined_annual_df['PRICE LOW (Rs.)'] = combined_annual_df.apply(
    lambda row: np.fmin(row['OPEN PRICE (Rs.)'], row['CLOSE PRICE (Rs.)'])
                if pd.isnull(row['PRICE LOW (Rs.)'])
                else row['PRICE LOW (Rs.)'], axis=1
)

filled_low_count = initial_missing_low - combined_annual_df['PRICE LOW (Rs.)'].isnull().sum()
print(f"Filled {filled_low_count} missing 'PRICE LOW (Rs.)' values with min(Open, Close).")

# Display summary of changes and info
print("\nDataFrame after imputing missing Open and Low prices:")
display(combined_annual_df.head())
display(combined_annual_df.tail())
combined_annual_df.info()

Filled 17 missing 'OPEN PRICE (Rs.)' values with previous day's close.
Filled 34 missing 'PRICE LOW (Rs.)' values with min(Open, Close).

DataFrame after imputing missing Open and Low prices:

,COMPANY ID,SHORT NAME,Date,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
0,ABL,AMANA BANK,2020-01-02,24.0,23.0,23.0,23.0,5.1,33178.1,763510.9
1,ABL,AMANA BANK,2020-01-03,24.0,23.0,23.0,23.0,3.0,7144.4,164322.2
2,ABL,AMANA BANK,2020-01-06,24.0,22.0,23.0,23.0,2.5,6102.4,140379.6
3,ABL,AMANA BANK,2020-01-07,24.0,23.0,23.0,24.0,1.1,1621.9,37305.7
4,ABL,AMANA BANK,2020-01-08,23.0,22.0,22.0,23.0,2.0,15604.4,344820.5

,COMPANY ID,SHORT NAME,Date,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.)
14922,UBC,UNION BANK,2025-12-24,14.9,14.6,14.8,14.8,35.0,50365.0,748629.3
14923,UBC,UNION BANK,2025-12-26,15.0,14.6,14.7,14.7,28.0,77013.0,1141505.0
14924,UBC,UNION BANK,2025-12-29,14.9,14.5,14.7,14.7,31.0,133398.0,1956986.2
14925,UBC,UNION BANK,2025-12-30,15.0,14.5,14.9,14.9,41.0,24504.0,360107.5
14926,UBC,UNION BANK,2025-12-31,15.0,14.6,14.9,14.9,34.0,52858.0,787381.8

<class 'pandas.core.frame.DataFrame'>
Index: 14927 entries, 0 to 14926
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   COMPANY ID          14927 non-null  object
 1   SHORT NAME          14927 non-null  object
 2   Date                14927 non-null  datetime64[ns]
 3   PRICE HIGH (Rs.)    14927 non-null  float64
 4   PRICE LOW (Rs.)     14927 non-null  float64
 5   CLOSE PRICE (Rs.)   14927 non-null  float64
 6   OPEN PRICE (Rs.)    14927 non-null  float64
 7   TRADE VOLUME (No.)  14927 non-null  float64
 8   SHARE VOLUME (No.)  14927 non-null  float64
 9   TURNOVER (Rs.)      14927 non-null  float64
dtypes: datetime64[ns](1), float64(7), object(2)
memory usage: 1.3+ MB

### Cleaning Market Index, FX, and Inflation Data

Now, I will load the pre-filtered datasets for the market index, exchange rate, and inflation, apply the requested cleaning steps (column renaming, date parsing, and dropping unnecessary columns), and then save the cleaned versions.

In [7]:
import pandas as pd

# --- Load Data ---
filtered_bank_data = pd.read_csv('/content/filtered_bank_data.csv')
filtered_exchange_rate_data = pd.read_csv('/content/filtered_exchange_rate_data.csv')
filtered_ccpi_df = pd.read_csv('/content/filtered_ccpi_data.csv')

print('Loaded filtered_bank_data, filtered_exchange_rate_data, and filtered_ccpi_df.')

# --- Clean filtered_bank_data ---
# Rename 'Bank' column to 'Sector_Index'
filtered_bank_data = filtered_bank_data.rename(columns={'Bank': 'Sector_Index'})
# Ensure 'Date' column is datetime type
filtered_bank_data['Date'] = pd.to_datetime(filtered_bank_data['Date'])

print('\nCleaned filtered_bank_data:')
display(filtered_bank_data.head())
filtered_bank_data.info()

Loaded filtered_bank_data, filtered_exchange_rate_data, and filtered_ccpi_df.

Cleaned filtered_bank_data:

        Date  Sector_Index
0 2020-01-02    632.707775
1 2020-01-03    632.707775
2 2020-01-06    628.686327
3 2020-01-07    612.600536
4 2020-01-08    589.812332

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1400 entries, 0 to 1399
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          1400 non-null   datetime64[ns]
 1   Sector_Index  1400 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 22.0 KB

In [8]:
# --- Clean filtered_exchange_rate_data ---
# Drop the 'Currency' column
if 'Currency' in filtered_exchange_rate_data.columns:
    filtered_exchange_rate_data = filtered_exchange_rate_data.drop(columns=['Currency'])
    print("Dropped 'Currency' column from filtered_exchange_rate_data.")
else:
    print("'Currency' column not found in filtered_exchange_rate_data.")
# Ensure 'Date' column is datetime type
filtered_exchange_rate_data['Date'] = pd.to_datetime(filtered_exchange_rate_data['Date'])

print('\nCleaned filtered_exchange_rate_data:')
display(filtered_exchange_rate_data.head())
filtered_exchange_rate_data.info()

Dropped 'Currency' column from filtered_exchange_rate_data.

Cleaned filtered_exchange_rate_data:

        Date  Exchange Rate
0 2025-12-31       309.9944
1 2025-12-30       309.8309
2 2025-12-29       309.7101
3 2025-12-26       309.7074
4 2025-12-24       309.6580

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1445 entries, 0 to 1444
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           1445 non-null   datetime64[ns]
 1   Exchange Rate  1445 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 22.7 KB

In [9]:
# --- Clean filtered_ccpi_df ---
# Ensure 'Date' column is datetime type
filtered_ccpi_df['Date'] = pd.to_datetime(filtered_ccpi_df['Date'])

# Shift the date forward by one month to prevent lookahead bias
filtered_ccpi_df['Date'] = filtered_ccpi_df['Date'] + pd.DateOffset(months=1)

print('\nCleaned filtered_ccpi_df (with date shifted by one month):')
display(filtered_ccpi_df.head())
filtered_ccpi_df.info()

Cleaned filtered_ccpi_df (with date shifted by one month):

   YoY_Inflation_%       Date
0              5.7 2020-02-01
1              6.2 2020-03-01
2              5.4 2020-04-01
3              5.2 2020-05-01
4              4.0 2020-06-01

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YoY_Inflation_%  72 non-null     float64
 1   Date             72 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 1.3 KB

### Merging All Cleaned Data into a Single Panel

Now that all individual datasets (`combined_annual_df`, `filtered_bank_data`, `filtered_exchange_rate_data`, and `filtered_ccpi_df`) are cleaned and preprocessed (including the one-month forward shift for inflation data to avoid lookahead bias), we will merge them into a single panel. To correctly handle the differing publication schedules of these financial indicators, we will use a nearest-prior-value join. This means for each stock's trading date, we will fetch the most recent available value from the market index, FX rate, and inflation datasets *prior to or on* that trading date.

In [10]:
# 1. Rename 'TRADING DATE' in combined_annual_df to 'Date' for consistency
combined_annual_df.rename(columns={'TRADING DATE': 'Date'}, inplace=True)

# Ensure all 'Date' columns are datetime type, which is a prerequisite for merge_asof
combined_annual_df['Date'] = pd.to_datetime(combined_annual_df['Date'])
filtered_bank_data['Date'] = pd.to_datetime(filtered_bank_data['Date'])
filtered_exchange_rate_data['Date'] = pd.to_datetime(filtered_exchange_rate_data['Date'])
# filtered_ccpi_df['Date'] is already datetime and shifted from previous step

print("Renamed 'TRADING DATE' to 'Date' in combined_annual_df and ensured all 'Date' columns are datetime type.")

# 2. Sort all DataFrames by their 'Date' column
# This is crucial for pd.merge_asof with direction='backward'
combined_annual_df.sort_values(by='Date', inplace=True)
filtered_bank_data.sort_values(by='Date', inplace=True)
filtered_exchange_rate_data.sort_values(by='Date', inplace=True)
filtered_ccpi_df.sort_values(by='Date', inplace=True)

print("All DataFrames sorted by 'Date'.")

# 3. Perform nearest-prior-value merges using pd.merge_asof

# Start with combined_annual_df as the left DataFrame
merged_df = combined_annual_df.copy()

# Merge with filtered_bank_data
merged_df = pd.merge_asof(merged_df,
                     filtered_bank_data,
                     on='Date',
                     direction='backward',
                     suffixes=('', '_Bank')) # Use suffixes to avoid column name clashes
print("Merged with filtered_bank_data using nearest-prior-value join.")

# Merge with filtered_exchange_rate_data
merged_df = pd.merge_asof(merged_df,
                     filtered_exchange_rate_data,
                     on='Date',
                     direction='backward',
                     suffixes=('', '_FX')) # Use suffixes
print("Merged with filtered_exchange_rate_data using nearest-prior-value join.")

# Merge with filtered_ccpi_df
merged_df = pd.merge_asof(merged_df,
                     filtered_ccpi_df,
                     on='Date',
                     direction='backward',
                     suffixes=('', '_Inflation')) # Use suffixes
print("Merged with filtered_ccpi_df using nearest-prior-value join.")

print("\nFinal merged DataFrame head (showing first 10 rows for better context):")
display(merged_df.head(10))

print("\nFinal merged DataFrame tail (showing last 10 rows):")
display(merged_df.tail(10))

print("\nFinal merged DataFrame info:")
merged_df.info()

print("\nChecking for any remaining NaNs in the newly merged columns:")
print(merged_df[['Sector_Index', 'Exchange Rate', 'YoY_Inflation_%']].isnull().sum())

Renamed 'TRADING DATE' to 'Date' in combined_annual_df and ensured all 'Date' columns are datetime type.
All DataFrames sorted by 'Date'.
Merged with filtered_bank_data using nearest-prior-value join.
Merged with filtered_exchange_rate_data using nearest-prior-value join.
Merged with filtered_ccpi_df using nearest-prior-value join.

Final merged DataFrame head (showing first 10 rows for better context):

,COMPANY ID,SHORT NAME,Date,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.),Sector_Index,Exchange Rate,YoY_Inflation_%
0,ABL,AMANA BANK,2020-01-02,24.0,23.0,23.0,23.0,5.1,33178.1,763510.9,632.707775,181.028,NaN
1,DFCC,DFCC BANK PLC,2020-01-02,91.7,90.0,90.0,91.7,25.0,4299.0,389018.1,632.707775,181.028,NaN
2,HDFC,HDFC,2020-01-02,31.8,30.7,30.8,30.8,7.0,1921.0,59110.7,632.707775,181.028,NaN
3,SDB,SANASA DEV. BANK,2020-01-02,63.9,62.0,63.9,62.5,6.0,83.0,5266.1,632.707775,181.028,NaN
4,SEYB,SEYLAN BANK,2020-01-02,53.5,52.0,52.5,53.5,73.0,153329.0,7994919.3,632.707775,181.028,NaN
5,UBC,UNION BANK,2020-01-02,13.1,13.0,13.0,13.0,13.0,5749.0,74747.4,632.707775,181.028,NaN
6,HNB,HNB,2020-01-02,173.9,172.2,172.3,173.9,13.0,663.0,114238.8,632.707775,181.028,NaN
7,NDB,NAT. DEV. BANK,2020-01-02,104.0,100.0,101.0,104.0,27.0,9876.0,994567.9,632.707775,181.028,NaN
8,NTB,NATIONS TRUST,2020-01-02,80.0,80.0,80.0,80.0,10.0,2864.0,229120.0,632.707775,181.028,NaN
9,PABC,PAN ASIA,2020-01-02,12.9,12.6,12.8,12.7,10.0,1095.0,13997.8,632.707775,181.028,NaN

Final merged DataFrame tail (showing last 10 rows):

,COMPANY ID,SHORT NAME,Date,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.),Sector_Index,Exchange Rate,YoY_Inflation_%
14917,NDB,NAT. DEV. BANK,2025-12-31,142.00,141.00,141.25,141.25,219.0,195071.0,27574779.00,1201.072386,309.9944,2.1
14918,ABL,AMANA BANK,2025-12-31,30.20,29.40,30.00,30.00,124.0,269536.0,8054994.60,1201.072386,309.9944,2.1
14919,HDFC,HDFC,2025-12-31,59.40,57.00,57.90,57.90,70.0,26431.0,1542856.20,1201.072386,309.9944,2.1
14920,SAMP,SAMPATH,2025-12-31,147.00,145.75,146.50,146.50,771.0,647508.0,94731361.00,1201.072386,309.9944,2.1
14921,SEYB,SEYLAN BANK,2025-12-31,106.00,103.00,105.00,105.00,81.0,28232.0,2964292.25,1201.072386,309.9944,2.1
14922,DFCC,DFCC BANK PLC,2025-12-31,153.25,146.50,148.00,148.00,578.0,526483.0,78716461.50,1201.072386,309.9944,2.1
14923,COMB,COMMERCIAL BANK,2025-12-31,203.00,200.00,200.75,200.75,396.0,251229.0,50575867.00,1201.072386,309.9944,2.1
14924,CBNK,CARGILLS BANK,2025-12-31,9.90,9.50,9.60,9.60,221.0,717739.0,6933872.20,1201.072386,309.9944,2.1
14925,HNB,HNB,2025-12-31,400.00,398.00,398.50,398.50,172.0,109595.0,43725363.50,1201.072386,309.9944,2.1
14926,UBC,UNION BANK,2025-12-31,15.00,14.60,14.90,14.90,34.0,52858.0,787381.80,1201.072386,309.9944,2.1

Final merged DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14927 entries, 0 to 14926
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   COMPANY ID          14927 non-null  object
 1   SHORT NAME          14927 non-null  object
 2   Date                14927 non-null  datetime64[ns]
 3   PRICE HIGH (Rs.)    14927 non-null  float64
 4   PRICE LOW (Rs.)     14927 non-null  float64
 5   CLOSE PRICE (Rs.)   14927 non-null  float64
 6   OPEN PRICE (Rs.)    14927 non-null  float64
 7   TRADE VOLUME (No.)  14927 non-null  float64
 8   SHARE VOLUME (No.)  14927 non-null  float64
 9   TURNOVER (Rs.)      14927 non-null  float64
 10  Sector_Index        14927 non-null  float64
 11  Exchange Rate       14927 non-null  float64
 12  YoY_Inflation_%     14690 non-null  float64
dtypes: datetime64[ns](1), float64(10), object(2)
memory usage: 1.5+ MB

Checking for any remaining NaNs in the newly merged columns:
Sector_Index         0
Exchange Rate        0
YoY_Inflation_%    237
dtype: int64

### Handling Initial Missing Macro Data

As noted, there might be some `NaN` values at the very beginning of the `merged_df` for macro indicators if the stock trading data starts earlier than the availability of `Sector_Index`, `Exchange Rate`, or `YoY_Inflation_%`. To prevent any form of lookahead bias, we will drop these initial rows rather than attempting to impute them, ensuring that all available macro data for a given date is strictly prior to or on that date.

In [11]:
print("Number of rows before dropping initial NaNs:", merged_df.shape[0])

# Drop rows where Sector_Index, Exchange Rate, or YoY_Inflation_% are NaN
# These NaNs typically occur at the beginning of the timeline where no prior macro data exists.
initial_nan_columns = ['Sector_Index', 'Exchange Rate', 'YoY_Inflation_%']
merged_df.dropna(subset=initial_nan_columns, inplace=True)

print("Number of rows after dropping initial NaNs:", merged_df.shape[0])

print("\nFinal merged DataFrame head (after dropping initial NaNs):")
display(merged_df.head(10))

print("\nFinal merged DataFrame tail:")
display(merged_df.tail(10))

print("\nFinal merged DataFrame info (after dropping initial NaNs):")
merged_df.info()

print("\nChecking for any remaining NaNs in macro columns:")
print(merged_df[initial_nan_columns].isnull().sum())

Number of rows before dropping initial NaNs: 14927
Number of rows after dropping initial NaNs: 14690

Final merged DataFrame head (after dropping initial NaNs):

,COMPANY ID,SHORT NAME,Date,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.),Sector_Index,Exchange Rate,YoY_Inflation_%
237,SDB,SANASA DEV. BANK,2020-02-03,59.000000,59.000000,58.1,59.000000,1.0,17.0,1003.0,589.812332,181.4017,5.7
238,NDB,NAT. DEV. BANK,2020-02-03,98.000000,97.100000,97.2,98.000000,28.0,8402.0,820442.2,589.812332,181.4017,5.7
239,SAMP,SAMPATH,2020-02-03,54.666667,54.066667,54.4,54.633333,171.0,558021.0,30373577.6,589.812332,181.4017,5.7
240,ABL,AMANA BANK,2020-02-03,23.000000,22.000000,23.0,23.000000,2.1,7250.0,161250.0,589.812332,181.4017,5.7
241,SEYB,SEYLAN BANK,2020-02-03,50.000000,49.500000,49.9,50.000000,23.0,7172.0,355287.0,589.812332,181.4017,5.7
242,DFCC,DFCC BANK PLC,2020-02-03,86.400000,84.900000,85.4,84.900000,58.0,11570.0,986505.2,589.812332,181.4017,5.7
243,HDFC,HDFC,2020-02-03,28.900000,26.000000,27.8,28.400000,8.0,296.0,8235.0,589.812332,181.4017,5.7
244,UBC,UNION BANK,2020-02-03,12.700000,12.100000,12.5,12.400000,22.0,58940.0,736842.0,589.812332,181.4017,5.7
245,NTB,NATIONS TRUST,2020-02-03,78.000000,77.800000,77.8,77.900000,9.0,262105.0,20443781.0,589.812332,181.4017,5.7
246,COMB,COMMERCIAL BANK,2020-02-03,95.000000,92.100000,92.4,93.000000,188.0,2013663.0,185413885.3,589.812332,181.4017,5.7

Final merged DataFrame tail:

,COMPANY ID,SHORT NAME,Date,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.),Sector_Index,Exchange Rate,YoY_Inflation_%
14917,NDB,NAT. DEV. BANK,2025-12-31,142.00,141.00,141.25,141.25,219.0,195071.0,27574779.00,1201.072386,309.9944,2.1
14918,ABL,AMANA BANK,2025-12-31,30.20,29.40,30.00,30.00,124.0,269536.0,8054994.60,1201.072386,309.9944,2.1
14919,HDFC,HDFC,2025-12-31,59.40,57.00,57.90,57.90,70.0,26431.0,1542856.20,1201.072386,309.9944,2.1
14920,SAMP,SAMPATH,2025-12-31,147.00,145.75,146.50,146.50,771.0,647508.0,94731361.00,1201.072386,309.9944,2.1
14921,SEYB,SEYLAN BANK,2025-12-31,106.00,103.00,105.00,105.00,81.0,28232.0,2964292.25,1201.072386,309.9944,2.1
14922,DFCC,DFCC BANK PLC,2025-12-31,153.25,146.50,148.00,148.00,578.0,526483.0,78716461.50,1201.072386,309.9944,2.1
14923,COMB,COMMERCIAL BANK,2025-12-31,203.00,200.00,200.75,200.75,396.0,251229.0,50575867.00,1201.072386,309.9944,2.1
14924,CBNK,CARGILLS BANK,2025-12-31,9.90,9.50,9.60,9.60,221.0,717739.0,6933872.20,1201.072386,309.9944,2.1
14925,HNB,HNB,2025-12-31,400.00,398.00,398.50,398.50,172.0,109595.0,43725363.50,1201.072386,309.9944,2.1
14926,UBC,UNION BANK,2025-12-31,15.00,14.60,14.90,14.90,34.0,52858.0,787381.80,1201.072386,309.9944,2.1

Final merged DataFrame info (after dropping initial NaNs):
<class 'pandas.core.frame.DataFrame'>
Index: 14690 entries, 237 to 14926
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   COMPANY ID          14690 non-null  object
 1   SHORT NAME          14690 non-null  object
 2   Date                14690 non-null  datetime64[ns]
 3   PRICE HIGH (Rs.)    14690 non-null  float64
 4   PRICE LOW (Rs.)     14690 non-null  float64
 5   CLOSE PRICE (Rs.)   14690 non-null  float64
 6   OPEN PRICE (Rs.)    14690 non-null  float64
 7   TRADE VOLUME (No.)  14690 non-null  float64
 8   SHARE VOLUME (No.)  14690 non-null  float64
 9   TURNOVER (Rs.)      14690 non-null  float64
 10  Sector_Index        14690 non-null  float64
 11  Exchange Rate       14690 non-null  float64
 12  YoY_Inflation_%     14690 non-null  float64
dtypes: datetime64[ns](1), float64(10), object(2)
memory usage: 1.6+ MB

Checking for any remaining NaNs in macro columns:
Sector_Index       0
Exchange Rate      0
YoY_Inflation_%    0
dtype: int64

### Feature Engineering: Technical Indicators (Per Stock)

To prepare the dataset for predictive modeling, we will create several technical indicators. It's critical that these calculations are performed *separately for each company* to prevent data leakage and ensure that the indicators reflect the specific stock's performance.

We will compute:

1.  **Returns:** Daily Return and Log Return.
2.  **Price Structure:** High-Low Range relative to Close Price, and Open-Close Change.
3.  **Trend Indicators:** 5-day, 10-day, and 20-day Simple Moving Averages (SMA) and Exponential Moving Averages (EMA) of the Close Price. Additionally, a ratio of Close Price to its 20-day EMA will be calculated.

In [12]:
import numpy as np

# Ensure the DataFrame is sorted by COMPANY ID and Date for correct rolling/shifting operations
merged_df.sort_values(by=['COMPANY ID', 'Date'], inplace=True)

# Group by 'COMPANY ID' to perform calculations independently for each stock
merged_df_grouped = merged_df.groupby('COMPANY ID')

# 1. Returns
# Daily Return: (Close Price_t - Close Price_{t-1}) / Close Price_{t-1}
merged_df['Daily_Return'] = merged_df_grouped['CLOSE PRICE (Rs.)'].pct_change()

# Log Return: log(Close Price_t / Close Price_{t-1})
merged_df['Log_Return'] = np.log(merged_df_grouped['CLOSE PRICE (Rs.)'].ffill() / merged_df_grouped['CLOSE PRICE (Rs.)'].ffill().shift(1))

# 2. Price Structure
# High-Low Range relative to Close
merged_df['High_Low_Range'] = (merged_df['PRICE HIGH (Rs.)'] - merged_df['PRICE LOW (Rs.)']) / merged_df['CLOSE PRICE (Rs.)']

# Open-Close Change
merged_df['Open_Close_Change'] = (merged_df['CLOSE PRICE (Rs.)'] - merged_df['OPEN PRICE (Rs.)']) / merged_df['OPEN PRICE (Rs.)']

# 3. Trend Indicators
# Define periods for moving averages
ma_periods = [5, 10, 20]

for period in ma_periods:
    # Simple Moving Average (SMA)
    merged_df[f'SMA_{period}'] = merged_df_grouped['CLOSE PRICE (Rs.)'].transform(lambda x: x.rolling(window=period).mean())

    # Exponential Moving Average (EMA)
    # Adjust=False is often preferred for consistency with older EMA definitions and stability
    merged_df[f'EMA_{period}'] = merged_df_grouped['CLOSE PRICE (Rs.)'].transform(lambda x: x.ewm(span=period, adjust=False).mean())

# Price-vs-20-day-average ratio (using EMA_20 as it's more responsive)
merged_df['Price_vs_EMA20_Ratio'] = merged_df['CLOSE PRICE (Rs.)'] / merged_df['EMA_20']

print("Feature engineering complete. Displaying head and info of the DataFrame with new features:")
display(merged_df.head(15))
merged_df.info()

print("\nChecking for NaNs in newly created feature columns:")
new_features = ['Daily_Return', 'Log_Return', 'High_Low_Range', 'Open_Close_Change'] + \
               [f'SMA_{p}' for p in ma_periods] + [f'EMA_{p}' for p in ma_periods] + \
               ['Price_vs_EMA20_Ratio']
print(merged_df[new_features].isnull().sum())

Feature engineering complete. Displaying head and info of the DataFrame with new features:

,COMPANY ID,SHORT NAME,Date,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.),...,Log_Return,High_Low_Range,Open_Close_Change,SMA_5,EMA_5,SMA_10,EMA_10,SMA_20,EMA_20,Price_vs_EMA20_Ratio
240,ABL,AMANA BANK,2020-02-03,23.0,22.0,23.0,23.0,2.1,7250.0,161250.0,...,NaN,0.043478,0.000000,NaN,23.000000,NaN,23.000000,NaN,23.000000,1.000000
259,ABL,AMANA BANK,2020-02-05,23.0,22.0,22.0,23.0,1.4,14691.0,327853.0,...,-0.044452,0.045455,-0.043478,NaN,22.666667,NaN,22.818182,NaN,22.904762,0.960499
272,ABL,AMANA BANK,2020-02-06,23.0,22.0,22.0,22.0,0.8,8155.5,179576.5,...,0.000000,0.045455,0.000000,NaN,22.444444,NaN,22.669421,NaN,22.818594,0.964126
280,ABL,AMANA BANK,2020-02-07,23.0,22.0,23.0,23.0,0.9,2223.3,49035.9,...,0.044452,0.043478,0.000000,NaN,22.629630,NaN,22.729527,NaN,22.835871,1.007187
284,ABL,AMANA BANK,2020-02-10,23.0,22.0,23.0,23.0,5.3,66318.0,1460116.9,...,0.000000,0.043478,0.000000,22.6,22.753086,NaN,22.778704,NaN,22.851502,1.006498
294,ABL,AMANA BANK,2020-02-11,23.0,22.0,22.0,23.0,1.0,53341.0,1174143.0,...,-0.044452,0.045455,-0.043478,22.4,22.502058,NaN,22.637121,NaN,22.770407,0.966166
314,ABL,AMANA BANK,2020-02-12,23.0,22.0,22.0,22.0,0.7,2456.3,54547.0,...,0.000000,0.045455,0.000000,22.4,22.334705,NaN,22.521281,NaN,22.697035,0.969290
318,ABL,AMANA BANK,2020-02-13,23.0,22.0,23.0,22.0,0.6,306.4,7043.7,...,0.044452,0.043478,0.045455,22.6,22.556470,NaN,22.608321,NaN,22.725889,1.012062
332,ABL,AMANA BANK,2020-02-14,23.0,22.0,22.0,22.0,3.0,37406.0,860082.9,...,-0.044452,0.045455,0.000000,22.4,22.370980,NaN,22.497717,NaN,22.656756,0.971013
349,ABL,AMANA BANK,2020-02-17,23.0,22.0,23.0,23.0,0.4,1200.0,26600.0,...,0.044452,0.043478,0.000000,22.4,22.580653,22.5,22.589041,NaN,22.689446,1.013687
355,ABL,AMANA BANK,2020-02-18,23.0,23.0,23.0,23.0,1.3,6261.2,144007.6,...,0.000000,0.000000,0.000000,22.6,22.720436,22.5,22.663761,NaN,22.719023,1.012367
370,ABL,AMANA BANK,2020-02-19,23.0,22.0,23.0,23.0,2.5,40361.9,888323.3,...,0.000000,0.043478,0.000000,22.8,22.813624,22.6,22.724895,NaN,22.745782,1.011176
386,ABL,AMANA BANK,2020-02-20,23.0,23.0,23.0,23.0,0.2,16.2,372.6,...,0.000000,0.000000,0.000000,22.8,22.875749,22.7,22.774914,NaN,22.769994,1.010101
398,ABL,AMANA BANK,2020-02-24,23.0,22.0,22.0,22.0,1.9,34237.8,753233.8,...,-0.044452,0.045455,0.000000,22.8,22.583833,22.6,22.634021,NaN,22.696661,0.969306
406,ABL,AMANA BANK,2020-02-25,23.0,22.0,22.0,22.0,0.7,8430.8,185677.6,...,0.000000,0.045455,0.000000,22.6,22.389222,22.5,22.518744,NaN,22.630312,0.972147

<class 'pandas.core.frame.DataFrame'>
Index: 14690 entries, 240 to 14926
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   COMPANY ID            14690 non-null  object
 1   SHORT NAME            14690 non-null  object
 2   Date                  14690 non-null  datetime64[ns]
 3   PRICE HIGH (Rs.)      14690 non-null  float64
 4   PRICE LOW (Rs.)       14690 non-null  float64
 5   CLOSE PRICE (Rs.)     14690 non-null  float64
 6   OPEN PRICE (Rs.)      14690 non-null  float64
 7   TRADE VOLUME (No.)    14690 non-null  float64
 8   SHARE VOLUME (No.)    14690 non-null  float64
 9   TURNOVER (Rs.)        14690 non-null  float64
 10  Sector_Index          14690 non-null  float64
 11  Exchange Rate         14690 non-null  float64
 12  YoY_Inflation_%       14690 non-null  float64
 13  Daily_Return          14677 non-null  float64
 14  Log_Return            14689 non-null  float64
 15  High_Low_Range        14690 non-null  float64
 16  Open_Close_Change     14690 non-null  float64
 17  SMA_5                 14638 non-null  float64
 18  EMA_5                 14690 non-null  float64
 19  SMA_10                14573 non-null  float64
 20  EMA_10                14690 non-null  float64
 21  SMA_20                14443 non-null  float64
 22  EMA_20                14690 non-null  float64
 23  Price_vs_EMA20_Ratio  14690 non-null  float64
dtypes: datetime64[ns](1), float64(21), object(2)
memory usage: 2.8+ MB

Checking for NaNs in newly created feature columns:
Daily_Return             13
Log_Return                1
High_Low_Range            0
Open_Close_Change         0
SMA_5                    52
SMA_10                  117
SMA_20                  247
EMA_5                     0
EMA_10                    0
EMA_20                    0
Price_vs_EMA20_Ratio      0
dtype: int64

### Feature Engineering: Volatility Indicators

In [13]:
merged_df_grouped = merged_df.groupby('COMPANY ID')

# Volatility: Rolling Standard Deviation of Daily Returns
merged_df['Vol_5Day'] = merged_df_grouped['Daily_Return'].transform(lambda x: x.rolling(window=5).std())
merged_df['Vol_20Day'] = merged_df_grouped['Daily_Return'].transform(lambda x: x.rolling(window=20).std())

print("Volatility indicators calculated.")
# Display first few rows with new features and check for NaNs
display(merged_df[['COMPANY ID', 'Date', 'Daily_Return', 'Vol_5Day', 'Vol_20Day']].head(10))
print(merged_df[['Vol_5Day', 'Vol_20Day']].isnull().sum())

Volatility indicators calculated.

    COMPANY ID       Date  Daily_Return  Vol_5Day  Vol_20Day
240        ABL 2020-02-03           NaN       NaN        NaN
259        ABL 2020-02-05     -0.043478       NaN        NaN
272        ABL 2020-02-06      0.000000       NaN        NaN
280        ABL 2020-02-07      0.045455       NaN        NaN
284        ABL 2020-02-10      0.000000       NaN        NaN
294        ABL 2020-02-11     -0.043478  0.037089        NaN
314        ABL 2020-02-12      0.000000  0.031447        NaN
318        ABL 2020-02-13      0.045455  0.037325        NaN
332        ABL 2020-02-14     -0.043478  0.037089        NaN
349        ABL 2020-02-17      0.045455  0.044469        NaN

Vol_5Day      65
Vol_20Day    260
dtype: int64

### Feature Engineering: Momentum and Oscillator Indicators

In [14]:
def calculate_rsi(series, window=14):
    delta = series.diff()
    gain = delta.where(delta > 0, 0)
    loss = -delta.where(delta < 0, 0)

    avg_gain = gain.ewm(com=window - 1, adjust=False).mean()
    avg_loss = loss.ewm(com=window - 1, adjust=False).mean()

    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

merged_df['RSI_14'] = merged_df_grouped['CLOSE PRICE (Rs.)'].transform(calculate_rsi)

print("RSI_14 calculated.")
# Display first few rows with new feature and check for NaNs
display(merged_df[['COMPANY ID', 'Date', 'CLOSE PRICE (Rs.)', 'RSI_14']].head(20))
print(merged_df[['RSI_14']].isnull().sum())

RSI_14 calculated.

    COMPANY ID       Date  CLOSE PRICE (Rs.)     RSI_14
240        ABL 2020-02-03               23.0        NaN
259        ABL 2020-02-05               22.0   0.000000
272        ABL 2020-02-06               22.0   0.000000
280        ABL 2020-02-07               23.0  53.698630
284        ABL 2020-02-10               23.0  53.698630
294        ABL 2020-02-11               22.0  33.090579
314        ABL 2020-02-12               22.0  33.090579
318        ABL 2020-02-13               23.0  53.698630
332        ABL 2020-02-14               22.0  40.323626
349        ABL 2020-02-17               23.0  52.945333
355        ABL 2020-02-18               23.0  52.945333
370        ABL 2020-02-19               23.0  52.945333
386        ABL 2020-02-20               23.0  52.945333
398        ABL 2020-02-24               22.0  41.219218
406        ABL 2020-02-25               22.0  41.219218
419        ABL 2020-02-26               22.0  41.219218
423        ABL 2020-02-27               23.0  53.955859
436        ABL 2020-02-28               22.0  43.747471
450        ABL 2020-03-02               22.0  43.747471
458        ABL 2020-03-03               23.0  53.869662

RSI_14    14
dtype: int64

In [15]:
macd_fast_period = 12
macd_slow_period = 26
macd_signal_period = 9

# Calculate EMA fast for each group using transform
ema_fast_grouped = merged_df_grouped['CLOSE PRICE (Rs.)'].transform(lambda x: x.ewm(span=macd_fast_period, adjust=False).mean())

# Calculate EMA slow for each group using transform
ema_slow_grouped = merged_df_grouped['CLOSE PRICE (Rs.)'].transform(lambda x: x.ewm(span=macd_slow_period, adjust=False).mean())

# Calculate MACD line
merged_df['MACD'] = ema_fast_grouped - ema_slow_grouped

# Calculate MACD Signal line based on the newly created MACD line, grouped again
# Re-grouping by 'COMPANY ID' for the signal line ensures that the EMA for the signal line is calculated correctly per company.
merged_df['MACD_Signal'] = merged_df.groupby('COMPANY ID')['MACD'].transform(lambda x: x.ewm(span=macd_signal_period, adjust=False).mean())

print("MACD and MACD_Signal calculated.")
# Display first few rows with new features and check for NaNs
display(merged_df[['COMPANY ID', 'Date', 'CLOSE PRICE (Rs.)', 'MACD', 'MACD_Signal']].head(30))
print(merged_df[['MACD', 'MACD_Signal']].isnull().sum())

MACD and MACD_Signal calculated.

    COMPANY ID       Date  CLOSE PRICE (Rs.)      MACD  MACD_Signal
240        ABL 2020-02-03               23.0  0.000000     0.000000
259        ABL 2020-02-05               22.0 -0.079772    -0.015954
272        ABL 2020-02-06               22.0 -0.141362    -0.041036
280        ABL 2020-02-07               23.0 -0.108234    -0.054476
284        ABL 2020-02-10               23.0 -0.081045    -0.059790
294        ABL 2020-02-11               22.0 -0.138592    -0.075550
314        ABL 2020-02-12               22.0 -0.182099    -0.096860
318        ABL 2020-02-13               23.0 -0.134339    -0.104356
332        ABL 2020-02-14               22.0 -0.175160    -0.118517
349        ABL 2020-02-17               23.0 -0.125375    -0.119888
355        ABL 2020-02-18               23.0 -0.084941    -0.112899
370        ABL 2020-02-19               23.0 -0.052294    -0.100778
386        ABL 2020-02-20               23.0 -0.026119    -0.085846
398        ABL 2020-02-24               22.0 -0.085087    -0.085694
406        ABL 2020-02-25               22.0 -0.130317    -0.094619
419        ABL 2020-02-26               22.0 -0.164268    -0.108549
423        ABL 2020-02-27               23.0 -0.109224    -0.108684
436        ABL 2020-02-28               22.0 -0.144626    -0.115872
450        ABL 2020-03-02               22.0 -0.170714    -0.126841
458        ABL 2020-03-03               23.0 -0.109436    -0.123360
475        ABL 2020-03-04               23.0 -0.060179    -0.110724
489        ABL 2020-03-05               23.0 -0.020902    -0.092759
503        ABL 2020-03-06               21.0 -0.149435    -0.104095
510        ABL 2020-03-10               22.0 -0.168663    -0.117008
524        ABL 2020-03-11               22.0 -0.181805    -0.129967
530        ABL 2020-03-12               22.0 -0.190029    -0.141980
549        ABL 2020-03-13               20.0 -0.353852    -0.184354
555        ABL 2020-03-20               19.0 -0.557942    -0.259072
571        ABL 2020-05-11               18.0 -0.791256    -0.365509
576        ABL 2020-05-12               18.0 -0.965035    -0.485414

MACD           0
MACD_Signal    0
dtype: int64

In [16]:
bollinger_window = 20
bollinger_num_std = 2

# Calculate Middle Band (20-day SMA)
merged_df['BB_Middle'] = merged_df_grouped['CLOSE PRICE (Rs.)'].transform(lambda x: x.rolling(window=bollinger_window).mean())

# Calculate 20-day rolling standard deviation
merged_df['BB_StdDev'] = merged_df_grouped['CLOSE PRICE (Rs.)'].transform(lambda x: x.rolling(window=bollinger_window).std())

# Calculate Upper and Lower Bands
merged_df['BB_Upper'] = merged_df['BB_Middle'] + (merged_df['BB_StdDev'] * bollinger_num_std)
merged_df['BB_Lower'] = merged_df['BB_Middle'] - (merged_df['BB_StdDev'] * bollinger_num_std)

# Calculate %B
merged_df['BB_Percent_B'] = (merged_df['CLOSE PRICE (Rs.)'] - merged_df['BB_Lower']) / (merged_df['BB_Upper'] - merged_df['BB_Lower'])

print("Bollinger Bands (Middle, Upper, Lower, %B) calculated.")
# Display first few rows with new features and check for NaNs
display(merged_df[['COMPANY ID', 'Date', 'CLOSE PRICE (Rs.)', 'BB_Middle', 'BB_Upper', 'BB_Lower', 'BB_Percent_B']].head(25))
print(merged_df[['BB_Middle', 'BB_Upper', 'BB_Lower', 'BB_Percent_B']].isnull().sum())

Bollinger Bands (Middle, Upper, Lower, %B) calculated.

,COMPANY ID,Date,CLOSE PRICE (Rs.),BB_Middle,BB_Upper,BB_Lower,BB_Percent_B
240,ABL,2020-02-03,23.0,NaN,NaN,NaN,NaN
259,ABL,2020-02-05,22.0,NaN,NaN,NaN,NaN
272,ABL,2020-02-06,22.0,NaN,NaN,NaN,NaN
280,ABL,2020-02-07,23.0,NaN,NaN,NaN,NaN
284,ABL,2020-02-10,23.0,NaN,NaN,NaN,NaN
294,ABL,2020-02-11,22.0,NaN,NaN,NaN,NaN
314,ABL,2020-02-12,22.0,NaN,NaN,NaN,NaN
318,ABL,2020-02-13,23.0,NaN,NaN,NaN,NaN
332,ABL,2020-02-14,22.0,NaN,NaN,NaN,NaN
349,ABL,2020-02-17,23.0,NaN,NaN,NaN,NaN
355,ABL,2020-02-18,23.0,NaN,NaN,NaN,NaN
370,ABL,2020-02-19,23.0,NaN,NaN,NaN,NaN
386,ABL,2020-02-20,23.0,NaN,NaN,NaN,NaN
398,ABL,2020-02-24,22.0,NaN,NaN,NaN,NaN
406,ABL,2020-02-25,22.0,NaN,NaN,NaN,NaN
419,ABL,2020-02-26,22.0,NaN,NaN,NaN,NaN
423,ABL,2020-02-27,23.0,NaN,NaN,NaN,NaN
436,ABL,2020-02-28,22.0,NaN,NaN,NaN,NaN
450,ABL,2020-03-02,22.0,NaN,NaN,NaN,NaN
458,ABL,2020-03-03,23.0,22.50,23.525978,21.474022,0.743670
475,ABL,2020-03-04,23.0,22.50,23.525978,21.474022,0.743670
489,ABL,2020-03-05,23.0,22.55,23.570836,21.529164,0.720408
503,ABL,2020-03-06,21.0,22.50,23.713954,21.286046,-0.117816
510,ABL,2020-03-10,22.0,22.45,23.659611,21.240389,0.313990
524,ABL,2020-03-11,22.0,22.40,23.596486,21.203514,0.332844

BB_Middle       247
BB_Upper        247
BB_Lower        247
BB_Percent_B    247
dtype: int64

In [17]:
roc_period = 10
merged_df['ROC_10Day'] = merged_df_grouped['CLOSE PRICE (Rs.)'].transform(lambda x: ((x / x.shift(roc_period)) - 1) * 100)

print("10-day Rate of Change calculated.")
# Display first few rows with new feature and check for NaNs
display(merged_df[['COMPANY ID', 'Date', 'CLOSE PRICE (Rs.)', 'ROC_10Day']].head(15))
print(merged_df[['ROC_10Day']].isnull().sum())

10-day Rate of Change calculated.

    COMPANY ID       Date  CLOSE PRICE (Rs.)  ROC_10Day
240        ABL 2020-02-03               23.0        NaN
259        ABL 2020-02-05               22.0        NaN
272        ABL 2020-02-06               22.0        NaN
280        ABL 2020-02-07               23.0        NaN
284        ABL 2020-02-10               23.0        NaN
294        ABL 2020-02-11               22.0        NaN
314        ABL 2020-02-12               22.0        NaN
318        ABL 2020-02-13               23.0        NaN
332        ABL 2020-02-14               22.0        NaN
349        ABL 2020-02-17               23.0        NaN
355        ABL 2020-02-18               23.0   0.000000
370        ABL 2020-02-19               23.0   4.545455
386        ABL 2020-02-20               23.0   4.545455
398        ABL 2020-02-24               22.0  -4.347826
406        ABL 2020-02-25               22.0  -4.347826

ROC_10Day    130
dtype: int64

In [18]:
import numpy as np # Ensure numpy is imported for np.where

stochastic_k_window = 14
stochastic_d_window = 3

def calculate_stochastic(df_group, k_window, d_window):
    lowest_low = df_group['PRICE LOW (Rs.)'].rolling(window=k_window).min()
    highest_high = df_group['PRICE HIGH (Rs.)'].rolling(window=k_window).max()

    # Avoid division by zero and handle potential inf/nan values carefully
    range_hl = highest_high - lowest_low

    # Calculate %K using np.where to handle cases where range_hl is zero or NaN
    # Ensure the result is a Series with the original index
    k_percent = pd.Series(np.where(
        (range_hl == 0) | range_hl.isna(),
        0.0, # Assign 0.0 if range is 0 or NaN, or choose np.nan if that's preferred for division by zero
        ((df_group['CLOSE PRICE (Rs.)'] - lowest_low) / range_hl) * 100
    ), index=df_group.index)

    # Calculate %D based on %K
    d_percent = k_percent.rolling(window=d_window).mean()

    # Return a DataFrame with both K and D, maintaining the original group index
    return pd.DataFrame({'Stochastic_K': k_percent, 'Stochastic_D': d_percent}, index=df_group.index)

# Apply the function to each group. The .apply() method on GroupBy will correctly handle
# a function that returns a DataFrame, concatenating the results.
stochastic_results_df = merged_df_grouped.apply(lambda x: calculate_stochastic(x, stochastic_k_window, stochastic_d_window), include_groups=False)

# Assign the results back to the merged_df, explicitly aligning indices by dropping the 'COMPANY ID' level
merged_df['Stochastic_K'] = stochastic_results_df['Stochastic_K'].droplevel(level=0)
merged_df['Stochastic_D'] = stochastic_results_df['Stochastic_D'].droplevel(level=0)

print("Stochastic %K and %D calculated.")
# Display first few rows with new features and check for NaNs
display(merged_df[['COMPANY ID', 'Date', 'CLOSE PRICE (Rs.)', 'PRICE HIGH (Rs.)', 'PRICE LOW (Rs.)', 'Stochastic_K', 'Stochastic_D']].head(20))
print(merged_df[['Stochastic_K', 'Stochastic_D']].isnull().sum())

Stochastic %K and %D calculated.

,COMPANY ID,Date,CLOSE PRICE (Rs.),PRICE HIGH (Rs.),PRICE LOW (Rs.),Stochastic_K,Stochastic_D
240,ABL,2020-02-03,23.0,23.0,22.0,0.0,NaN
259,ABL,2020-02-05,22.0,23.0,22.0,0.0,NaN
272,ABL,2020-02-06,22.0,23.0,22.0,0.0,0.000000
280,ABL,2020-02-07,23.0,23.0,22.0,0.0,0.000000
284,ABL,2020-02-10,23.0,23.0,22.0,0.0,0.000000
294,ABL,2020-02-11,22.0,23.0,22.0,0.0,0.000000
314,ABL,2020-02-12,22.0,23.0,22.0,0.0,0.000000
318,ABL,2020-02-13,23.0,23.0,22.0,0.0,0.000000
332,ABL,2020-02-14,22.0,23.0,22.0,0.0,0.000000
349,ABL,2020-02-17,23.0,23.0,22.0,0.0,0.000000
355,ABL,2020-02-18,23.0,23.0,23.0,0.0,0.000000
370,ABL,2020-02-19,23.0,23.0,22.0,0.0,0.000000
386,ABL,2020-02-20,23.0,23.0,23.0,0.0,0.000000
398,ABL,2020-02-24,22.0,23.0,22.0,0.0,0.000000
406,ABL,2020-02-25,22.0,23.0,22.0,0.0,0.000000
419,ABL,2020-02-26,22.0,22.0,22.0,0.0,0.000000
423,ABL,2020-02-27,23.0,23.0,22.0,100.0,33.333333
436,ABL,2020-02-28,22.0,22.0,22.0,0.0,33.333333
450,ABL,2020-03-02,22.0,23.0,22.0,0.0,33.333333
458,ABL,2020-03-03,23.0,23.0,22.0,100.0,33.333333

Stochastic_K     0
Stochastic_D    26
dtype: int64

### Feature Engineering: Liquidity Indicators

In [19]:
merged_df_grouped = merged_df.groupby('COMPANY ID') # Re-group as previous operations might have changed the dataframe structure, although `transform` and `apply` should preserve it.

# Volume Change: Percentage change in Trade Volume
merged_df['Volume_Change'] = merged_df_grouped['TRADE VOLUME (No.)'].pct_change()

# Turnover relative to its 5-day average
merged_df['SMA_5_Turnover'] = merged_df_grouped['TURNOVER (Rs.)'].transform(lambda x: x.rolling(window=5).mean())
merged_df['Turnover_vs_SMA5'] = merged_df['TURNOVER (Rs.)'] / merged_df['SMA_5_Turnover']

print("Liquidity indicators calculated.")
# Display first few rows with new features and check for NaNs
display(merged_df[['COMPANY ID', 'Date', 'TRADE VOLUME (No.)', 'Volume_Change', 'TURNOVER (Rs.)', 'SMA_5_Turnover', 'Turnover_vs_SMA5']].head(10))
print(merged_df[['Volume_Change', 'Turnover_vs_SMA5']].isnull().sum())

Liquidity indicators calculated.

,COMPANY ID,Date,TRADE VOLUME (No.),Volume_Change,TURNOVER (Rs.),SMA_5_Turnover,Turnover_vs_SMA5
240,ABL,2020-02-03,2.1,NaN,161250.0,NaN,NaN
259,ABL,2020-02-05,1.4,-0.333333,327853.0,NaN,NaN
272,ABL,2020-02-06,0.8,-0.428571,179576.5,NaN,NaN
280,ABL,2020-02-07,0.9,0.125000,49035.9,NaN,NaN
284,ABL,2020-02-10,5.3,4.888889,1460116.9,435566.46,3.352225
294,ABL,2020-02-11,1.0,-0.811321,1174143.0,638145.06,1.839931
314,ABL,2020-02-12,0.7,-0.300000,54547.0,583483.86,0.093485
318,ABL,2020-02-13,0.6,-0.142857,7043.7,548977.30,0.012831
332,ABL,2020-02-14,3.0,4.000000,860082.9,711186.70,1.209363
349,ABL,2020-02-17,0.4,-0.866667,26600.0,424483.32,0.062664

Volume_Change       13
Turnover_vs_SMA5    52
dtype: int64

### Feature Engineering: Market & Macro Context

In [20]:
import numpy as np

# Re-group the DataFrame by 'COMPANY ID' to ensure calculations are company-specific
merged_df_grouped = merged_df.groupby('COMPANY ID')

# 1. Sector Index Return
# Calculate day-over-day change in the banking index, grouped by company ID
# Since Sector_Index is constant for a given date across companies, this correctly calculates daily market return.
merged_df['Sector_Index_Return'] = merged_df_grouped['Sector_Index'].pct_change()

# 2. USD/LKR Return
# Calculate day-over-day change in the exchange rate, grouped by company ID
# Similar to Sector_Index_Return, Exchange Rate is constant for a given date across companies.
merged_df['USD_LKR_Return'] = merged_df_grouped['Exchange Rate'].pct_change()

# 3. Relative Strength
# How much a stock's return beats or lags the sector that day
merged_df['Relative_Strength'] = merged_df['Daily_Return'] - merged_df['Sector_Index_Return']

# 4. Rolling 20-day Beta
beta_window = 20

# Calculate rolling covariance of Daily_Return with Sector_Index_Return for each company
# Using .apply(lambda x: ...) to ensure the result aligns with the original DataFrame's index correctly
merged_df['Rolling_Covariance'] = merged_df_grouped.apply(
    lambda x: x['Daily_Return'].rolling(window=beta_window).cov(x['Sector_Index_Return']),
    include_groups=False # Added to resolve DeprecationWarning
).droplevel(0)

# Calculate rolling variance of Sector_Index_Return for each company
merged_df['Rolling_Variance_Sector'] = merged_df_grouped['Sector_Index_Return'].transform(
    lambda x: x.rolling(window=beta_window).var()
)

# Calculate Beta, handling potential division by zero or zero variance
# Replace inf/-inf values that can result from division by zero/very small numbers with NaN
merged_df['Rolling_20Day_Beta'] = (
    merged_df['Rolling_Covariance'] / merged_df['Rolling_Variance_Sector']
).replace([np.inf, -np.inf], np.nan)

# Drop temporary covariance and variance columns
merged_df.drop(columns=['Rolling_Covariance', 'Rolling_Variance_Sector'], inplace=True)

print("Market & Macro context features calculated.")
# Display first few rows with new features and check for NaNs
display(merged_df[[
    'COMPANY ID', 'Date', 'Daily_Return', 'Sector_Index', 'Sector_Index_Return',
    'Exchange Rate', 'USD_LKR_Return', 'Relative_Strength', 'Rolling_20Day_Beta'
]].head(25))

print("\nChecking for NaNs in newly created Market & Macro context feature columns:")
market_macro_features = ['Sector_Index_Return', 'USD_LKR_Return', 'Relative_Strength', 'Rolling_20Day_Beta']
print(merged_df[market_macro_features].isnull().sum().sort_values(ascending=False))

Market & Macro context features calculated.

,COMPANY ID,Date,Daily_Return,Sector_Index,Sector_Index_Return,Exchange Rate,USD_LKR_Return,Relative_Strength,Rolling_20Day_Beta
240,ABL,2020-02-03,NaN,589.812332,NaN,181.4017,NaN,NaN,NaN
259,ABL,2020-02-05,-0.043478,591.152815,0.002273,181.4781,4.211647e-04,-0.045751,NaN
272,ABL,2020-02-06,0.000000,591.152815,0.000000,181.3973,-4.452328e-04,0.000000,NaN
280,ABL,2020-02-07,0.045455,597.855228,0.011338,181.3408,-3.114710e-04,0.034117,NaN
284,ABL,2020-02-10,0.000000,603.217158,0.008969,181.3709,1.659858e-04,-0.008969,NaN
294,ABL,2020-02-11,-0.043478,603.217158,0.000000,181.4241,2.933216e-04,-0.043478,NaN
314,ABL,2020-02-12,0.000000,592.493298,-0.017778,181.4240,-5.511947e-07,0.017778,NaN
318,ABL,2020-02-13,0.045455,599.195710,0.011312,181.4481,1.328380e-04,0.034142,NaN
332,ABL,2020-02-14,-0.043478,599.195710,0.000000,181.4571,4.960096e-05,-0.043478,NaN
349,ABL,2020-02-17,0.045455,589.812332,-0.015660,181.4757,1.025036e-04,0.061115,NaN
355,ABL,2020-02-18,0.000000,589.812332,0.000000,181.5334,3.179489e-04,0.000000,NaN
370,ABL,2020-02-19,0.000000,589.812332,0.000000,181.6199,4.764963e-04,0.000000,NaN
386,ABL,2020-02-20,0.000000,580.428954,-0.015909,181.8976,1.529017e-03,0.015909,NaN
398,ABL,2020-02-24,-0.043478,563.002681,-0.030023,181.8423,-3.040172e-04,-0.013455,NaN
406,ABL,2020-02-25,0.000000,563.002681,0.000000,181.7795,-3.453542e-04,0.000000,NaN
419,ABL,2020-02-26,0.000000,542.895442,-0.035714,181.7458,-1.853894e-04,0.035714,NaN
423,ABL,2020-02-27,0.045455,537.533512,-0.009877,181.6870,-3.235288e-04,0.055331,NaN
436,ABL,2020-02-28,-0.043478,505.361930,-0.059850,181.8071,6.610269e-04,0.016372,NaN
450,ABL,2020-03-02,0.000000,534.852547,0.058355,181.9261,6.545399e-04,-0.058355,NaN
458,ABL,2020-03-03,0.045455,530.831099,-0.007519,182.0821,8.574910e-04,0.052973,NaN
475,ABL,2020-03-04,0.000000,516.085791,-0.027778,182.1086,1.455387e-04,0.027778,0.325909
489,ABL,2020-03-05,0.000000,509.383378,-0.012987,182.0347,-4.058018e-04,0.012987,0.367464
503,ABL,2020-03-06,-0.086957,502.680965,-0.013158,181.9223,-6.174647e-04,-0.073799,0.416544
510,ABL,2020-03-10,0.047619,482.573727,-0.040000,181.8312,-5.007632e-04,0.087619,0.168114
524,ABL,2020-03-11,0.000000,495.978552,0.027778,182.4495,3.400407e-03,-0.027778,0.155633

Checking for NaNs in newly created Market & Macro context feature columns:
Rolling_20Day_Beta     260
Sector_Index_Return     13
USD_LKR_Return          13
Relative_Strength       13
dtype: int64

### Feature Engineering: Calendar Features

In [21]:
import numpy as np

# Ensure 'Date' column is datetime type
merged_df['Date'] = pd.to_datetime(merged_df['Date'])

# 1. Cyclical encoding of Day of Week
# Day of week: Monday=0, Sunday=6
merged_df['Day_of_Week'] = merged_df['Date'].dt.dayofweek
merged_df['Day_of_Week_Sin'] = np.sin(2 * np.pi * merged_df['Day_of_Week'] / 7)
merged_df['Day_of_Week_Cos'] = np.cos(2 * np.pi * merged_df['Day_of_Week'] / 7)

# 2. Cyclical encoding of Month
# Month: January=1, December=12
merged_df['Month'] = merged_df['Date'].dt.month
merged_df['Month_Sin'] = np.sin(2 * np.pi * merged_df['Month'] / 12)
merged_df['Month_Cos'] = np.cos(2 * np.pi * merged_df['Month'] / 12)

# 3. Quarter-end-month flag
# Quarters typically end in March (3), June (6), September (9), December (12)
merged_df['Is_Quarter_End_Month'] = merged_df['Month'].isin([3, 6, 9, 12]).astype(int)

print("Calendar features calculated.")
# Display first few rows with new features and check for NaNs
display(merged_df[[
    'COMPANY ID', 'Date', 'Day_of_Week', 'Day_of_Week_Sin', 'Day_of_Week_Cos',
    'Month', 'Month_Sin', 'Month_Cos', 'Is_Quarter_End_Month'
]].head(25))

print("\nChecking for NaNs in newly created Calendar features columns:")
calendar_features = ['Day_of_Week', 'Day_of_Week_Sin', 'Day_of_Week_Cos', 'Month', 'Month_Sin', 'Month_Cos', 'Is_Quarter_End_Month']
print(merged_df[calendar_features].isnull().sum().sort_values(ascending=False))

Calendar features calculated.

,COMPANY ID,Date,Day_of_Week,Day_of_Week_Sin,Day_of_Week_Cos,Month,Month_Sin,Month_Cos,Is_Quarter_End_Month
240,ABL,2020-02-03,0,0.000000,1.000000,2,0.866025,5.000000e-01,0
259,ABL,2020-02-05,2,0.974928,-0.222521,2,0.866025,5.000000e-01,0
272,ABL,2020-02-06,3,0.433884,-0.900969,2,0.866025,5.000000e-01,0
280,ABL,2020-02-07,4,-0.433884,-0.900969,2,0.866025,5.000000e-01,0
284,ABL,2020-02-10,0,0.000000,1.000000,2,0.866025,5.000000e-01,0
294,ABL,2020-02-11,1,0.781831,0.623490,2,0.866025,5.000000e-01,0
314,ABL,2020-02-12,2,0.974928,-0.222521,2,0.866025,5.000000e-01,0
318,ABL,2020-02-13,3,0.433884,-0.900969,2,0.866025,5.000000e-01,0
332,ABL,2020-02-14,4,-0.433884,-0.900969,2,0.866025,5.000000e-01,0
349,ABL,2020-02-17,0,0.000000,1.000000,2,0.866025,5.000000e-01,0
355,ABL,2020-02-18,1,0.781831,0.623490,2,0.866025,5.000000e-01,0
370,ABL,2020-02-19,2,0.974928,-0.222521,2,0.866025,5.000000e-01,0
386,ABL,2020-02-20,3,0.433884,-0.900969,2,0.866025,5.000000e-01,0
398,ABL,2020-02-24,0,0.000000,1.000000,2,0.866025,5.000000e-01,0
406,ABL,2020-02-25,1,0.781831,0.623490,2,0.866025,5.000000e-01,0
419,ABL,2020-02-26,2,0.974928,-0.222521,2,0.866025,5.000000e-01,0
423,ABL,2020-02-27,3,0.433884,-0.900969,2,0.866025,5.000000e-01,0
436,ABL,2020-02-28,4,-0.433884,-0.900969,2,0.866025,5.000000e-01,0
450,ABL,2020-03-02,0,0.000000,1.000000,3,1.000000,6.123234e-17,1
458,ABL,2020-03-03,1,0.781831,0.623490,3,1.000000,6.123234e-17,1
475,ABL,2020-03-04,2,0.974928,-0.222521,3,1.000000,6.123234e-17,1
489,ABL,2020-03-05,3,0.433884,-0.900969,3,1.000000,6.123234e-17,1
503,ABL,2020-03-06,4,-0.433884,-0.900969,3,1.000000,6.123234e-17,1
510,ABL,2020-03-10,1,0.781831,0.623490,3,1.000000,6.123234e-17,1
524,ABL,2020-03-11,2,0.974928,-0.222521,3,1.000000,6.123234e-17,1

Checking for NaNs in newly created Calendar features columns:
Day_of_Week             0
Day_of_Week_Sin         0
Day_of_Week_Cos         0
Month                   0
Month_Sin               0
Month_Cos               0
Is_Quarter_End_Month    0
dtype: int64

### Target Variable Creation: 5-Day-Ahead Price and Return

Now, we will create the target variables required for predictive modeling. We need to define:

1.  **5-Day-Ahead Close Price (`Target_Close_5Day_Ahead`):** This is the closing price of a stock 5 trading days into the future. This will serve as a direct regression target.
2.  **5-Day-Ahead Return (`Target_Return_5Day_Ahead`):** This represents the percentage change in the closing price over the next 5 trading days. This is often a more robust target for forecasting as it normalizes price movements.

These calculations will be performed per company to maintain the integrity of the time series and prevent data leakage.

In [30]:
merged_df_grouped = merged_df.groupby('COMPANY ID')

# Calculate Close price and Return targets for every horizon from t+1 to t+5
for h in range(1, 6):
    merged_df[f'Target_Close_{h}Day_Ahead'] = merged_df_grouped['CLOSE PRICE (Rs.)'].shift(-h)
    merged_df[f'Target_Return_{h}Day_Ahead'] = (merged_df[f'Target_Close_{h}Day_Ahead'] / merged_df['CLOSE PRICE (Rs.)']) - 1

print("Target variables created for horizons t+1 through t+5.")

target_close_cols = [f'Target_Close_{h}Day_Ahead' for h in range(1, 6)]
target_return_cols = [f'Target_Return_{h}Day_Ahead' for h in range(1, 6)]

display(merged_df[['COMPANY ID', 'Date', 'CLOSE PRICE (Rs.)'] + target_return_cols].tail(10))

print("\nChecking for NaNs in newly created target columns:")
print(merged_df[target_close_cols + target_return_cols].isnull().sum().sort_values(ascending=False))

Target variables created for horizons t+1 through t+5.

,COMPANY ID,Date,CLOSE PRICE (Rs.),Target_Return_1Day_Ahead,Target_Return_2Day_Ahead,Target_Return_3Day_Ahead,Target_Return_4Day_Ahead,Target_Return_5Day_Ahead
14737,UBC,2025-12-10,14.6,0.020548,0.013699,-0.006849,-0.006849,-0.006849
14746,UBC,2025-12-11,14.9,-0.006711,-0.026846,-0.026846,-0.026846,-0.026846
14769,UBC,2025-12-12,14.8,-0.020270,-0.020270,-0.020270,-0.020270,-0.013514
14773,UBC,2025-12-15,14.5,0.000000,0.000000,0.000000,0.006897,0.020690
14790,UBC,2025-12-16,14.5,0.000000,0.000000,0.006897,0.020690,0.020690
14805,UBC,2025-12-17,14.5,0.000000,0.006897,0.020690,0.020690,NaN
14812,UBC,2025-12-18,14.5,0.006897,0.020690,0.020690,NaN,NaN
14835,UBC,2025-12-19,14.6,0.013699,0.013699,NaN,NaN,NaN
14843,UBC,2025-12-22,14.8,0.000000,NaN,NaN,NaN,NaN
14850,UBC,2025-12-23,14.8,NaN,NaN,NaN,NaN,NaN

Checking for NaNs in newly created target columns:
Target_Return_5Day_Ahead    65
Target_Close_5Day_Ahead     65
Target_Return_4Day_Ahead    52
Target_Close_4Day_Ahead     52
Target_Return_3Day_Ahead    39
Target_Close_3Day_Ahead     39
Target_Return_2Day_Ahead    26
Target_Close_2Day_Ahead     26
Target_Close_1Day_Ahead     13
Target_Return_1Day_Ahead    13
dtype: int64

In [31]:
print("First 10 rows of the final merged DataFrame:")
display(merged_df.head(10))

print("\nLast 10 rows of the final merged DataFrame:")
display(merged_df.tail(10))

First 10 rows of the final merged DataFrame:

,COMPANY ID,Date,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.),Sector_Index,...,Target_Close_5Day_Ahead,Target_Return_5Day_Ahead,Target_Close_1Day_Ahead,Target_Return_1Day_Ahead,Target_Close_2Day_Ahead,Target_Return_2Day_Ahead,Target_Close_3Day_Ahead,Target_Return_3Day_Ahead,Target_Close_4Day_Ahead,Target_Return_4Day_Ahead
475,ABL,2020-03-04,23.0,22.0,23.0,22.0,1.6,20293.5,446860.5,516.085791,...,22.0,-0.043478,23.0,0.000000,21.0,-0.086957,22.0,-0.043478,22.0,-0.043478
489,ABL,2020-03-05,23.0,22.0,23.0,23.0,1.1,600.4,13309.1,509.383378,...,20.0,-0.130435,21.0,-0.086957,22.0,-0.043478,22.0,-0.043478,22.0,-0.043478
503,ABL,2020-03-06,22.0,21.0,21.0,21.0,1.7,17043.8,372170.5,502.680965,...,19.0,-0.095238,22.0,0.047619,22.0,0.047619,22.0,0.047619,20.0,-0.047619
510,ABL,2020-03-10,22.0,20.0,22.0,22.0,3.7,15695.5,332562.2,482.573727,...,18.0,-0.181818,22.0,0.000000,22.0,0.000000,20.0,-0.090909,19.0,-0.136364
524,ABL,2020-03-11,22.0,21.0,22.0,22.0,1.1,5150.5,109561.0,495.978552,...,18.0,-0.181818,22.0,0.000000,20.0,-0.090909,19.0,-0.136364,18.0,-0.181818
530,ABL,2020-03-12,22.0,21.0,22.0,22.0,1.5,3205.2,67814.0,469.168901,...,19.0,-0.136364,20.0,-0.090909,19.0,-0.136364,18.0,-0.181818,18.0,-0.181818
549,ABL,2020-03-13,21.0,19.0,20.0,20.0,3.1,14595.7,290721.2,469.168901,...,20.0,0.000000,19.0,-0.050000,18.0,-0.100000,18.0,-0.100000,19.0,-0.050000
555,ABL,2020-03-20,20.0,19.0,19.0,20.0,2.0,6751.0,130679.5,443.699732,...,19.0,0.000000,18.0,-0.052632,18.0,-0.052632,19.0,0.000000,20.0,0.052632
571,ABL,2020-05-11,18.0,18.0,18.0,18.0,0.3,1100.0,19800.0,443.700000,...,19.0,0.055556,18.0,0.000000,19.0,0.055556,20.0,0.111111,19.0,0.055556
576,ABL,2020-05-12,20.0,17.0,18.0,18.0,1.9,583650.2,11086943.7,443.700000,...,20.0,0.111111,19.0,0.055556,20.0,0.111111,19.0,0.055556,19.0,0.055556

Last 10 rows of the final merged DataFrame:

,COMPANY ID,Date,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.),Sector_Index,...,Target_Close_5Day_Ahead,Target_Return_5Day_Ahead,Target_Close_1Day_Ahead,Target_Return_1Day_Ahead,Target_Close_2Day_Ahead,Target_Return_2Day_Ahead,Target_Close_3Day_Ahead,Target_Return_3Day_Ahead,Target_Close_4Day_Ahead,Target_Return_4Day_Ahead
14737,UBC,2025-12-10,14.7,14.4,14.6,14.6,66.0,128537.0,1879667.3,1195.710456,...,14.5,-0.006849,14.9,0.020548,14.8,0.013699,14.5,-0.006849,14.5,-0.006849
14746,UBC,2025-12-11,14.9,14.6,14.9,14.9,57.0,408775.0,6035038.3,1205.093834,...,14.5,-0.026846,14.8,-0.006711,14.5,-0.026846,14.5,-0.026846,14.5,-0.026846
14769,UBC,2025-12-12,15.0,14.7,14.8,14.8,41.0,726315.0,10819510.7,1205.093834,...,14.6,-0.013514,14.5,-0.020270,14.5,-0.020270,14.5,-0.020270,14.5,-0.020270
14773,UBC,2025-12-15,15.0,14.5,14.5,14.5,82.0,150709.0,2206303.1,1206.434316,...,14.8,0.020690,14.5,0.000000,14.5,0.000000,14.5,0.000000,14.6,0.006897
14790,UBC,2025-12-16,14.5,14.4,14.5,14.5,65.0,113412.0,1644448.8,1209.115282,...,14.8,0.020690,14.5,0.000000,14.5,0.000000,14.6,0.006897,14.8,0.020690
14805,UBC,2025-12-17,15.0,14.4,14.5,14.5,40.0,90715.0,1324339.1,1211.796247,...,NaN,NaN,14.5,0.000000,14.6,0.006897,14.8,0.020690,14.8,0.020690
14812,UBC,2025-12-18,15.0,14.5,14.5,14.5,40.0,189586.0,2800478.4,1209.115282,...,NaN,NaN,14.6,0.006897,14.8,0.020690,14.8,0.020690,NaN,NaN
14835,UBC,2025-12-19,14.8,14.4,14.6,14.6,43.0,66886.0,984406.1,1206.434316,...,NaN,NaN,14.8,0.013699,14.8,0.013699,NaN,NaN,NaN,NaN
14843,UBC,2025-12-22,14.9,14.4,14.8,14.8,26.0,31060.0,456755.0,1203.753351,...,NaN,NaN,14.8,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
14850,UBC,2025-12-23,15.0,14.7,14.8,14.8,38.0,52136.0,770821.2,1197.050938,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 10: Final Data Cleanup

Now that all features and target variables have been generated, we will perform a final cleanup to prepare the dataset for modeling. This involves:

1.  **Handling Infinite Values:** Convert any `inf` or `-inf` values (which can result from division by zero in return or ratio calculations) to `NaN`.
2.  **Dropping Rows with Missing Values:** Remove any rows that still contain `NaN` values. This will effectively eliminate the initial warm-up periods for rolling window calculations (where insufficient historical data exists) and the last few entries for each company where target variables could not be computed (due to `shift(-5)`).
3.  **Dropping Redundant Columns:** Remove the 'SHORT NAME' column, as it's a descriptive column and not a feature for modeling.

In [32]:
import numpy as np

print("Shape of DataFrame before final cleanup:", merged_df.shape)

# 1. Convert any infinite values to NaN
# This handles cases where division by zero might have resulted in inf/-inf
initial_inf_count = merged_df.isin([np.inf, -np.inf]).sum().sum()
if initial_inf_count > 0:
    merged_df.replace([np.inf, -np.inf], np.nan, inplace=True)
    print(f"Converted {initial_inf_count} infinite values to NaN.")
else:
    print("No infinite values found in the DataFrame.")

# 2. Drop all rows with any remaining NaN values
initial_rows = merged_df.shape[0]
merged_df.dropna(inplace=True)
rows_dropped_nan = initial_rows - merged_df.shape[0]
print(f"Dropped {rows_dropped_nan} rows due to missing values (NaNs).")

# 3. Drop the 'SHORT NAME' column
if 'SHORT NAME' in merged_df.columns:
    merged_df.drop(columns=['SHORT NAME'], inplace=True)
    print("Dropped 'SHORT NAME' column.")
else:
    print("'SHORT NAME' column not found.")

print("\nShape of DataFrame after final cleanup:", merged_df.shape)
print("\nFinal DataFrame head after cleanup:")
display(merged_df.head())
print("\nFinal DataFrame info after cleanup:")
merged_df.info()

print("\nFinal check for NaNs in the entire DataFrame:")
print(merged_df.isnull().sum().sum())

Shape of DataFrame before final cleanup: (14365, 57)
No infinite values found in the DataFrame.
Dropped 65 rows due to missing values (NaNs).
'SHORT NAME' column not found.

Shape of DataFrame after final cleanup: (14300, 57)

Final DataFrame head after cleanup:

,COMPANY ID,Date,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.),Sector_Index,...,Target_Close_5Day_Ahead,Target_Return_5Day_Ahead,Target_Close_1Day_Ahead,Target_Return_1Day_Ahead,Target_Close_2Day_Ahead,Target_Return_2Day_Ahead,Target_Close_3Day_Ahead,Target_Return_3Day_Ahead,Target_Close_4Day_Ahead,Target_Return_4Day_Ahead
475,ABL,2020-03-04,23.0,22.0,23.0,22.0,1.6,20293.5,446860.5,516.085791,...,22.0,-0.043478,23.0,0.000000,21.0,-0.086957,22.0,-0.043478,22.0,-0.043478
489,ABL,2020-03-05,23.0,22.0,23.0,23.0,1.1,600.4,13309.1,509.383378,...,20.0,-0.130435,21.0,-0.086957,22.0,-0.043478,22.0,-0.043478,22.0,-0.043478
503,ABL,2020-03-06,22.0,21.0,21.0,21.0,1.7,17043.8,372170.5,502.680965,...,19.0,-0.095238,22.0,0.047619,22.0,0.047619,22.0,0.047619,20.0,-0.047619
510,ABL,2020-03-10,22.0,20.0,22.0,22.0,3.7,15695.5,332562.2,482.573727,...,18.0,-0.181818,22.0,0.000000,22.0,0.000000,20.0,-0.090909,19.0,-0.136364
524,ABL,2020-03-11,22.0,21.0,22.0,22.0,1.1,5150.5,109561.0,495.978552,...,18.0,-0.181818,22.0,0.000000,20.0,-0.090909,19.0,-0.136364,18.0,-0.181818

Final DataFrame info after cleanup:
<class 'pandas.core.frame.DataFrame'>
Index: 14300 entries, 475 to 14790
Data columns (total 57 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   COMPANY ID                14300 non-null  object
 1   Date                      14300 non-null  datetime64[ns]
 2   PRICE HIGH (Rs.)          14300 non-null  float64
 3   PRICE LOW (Rs.)           14300 non-null  float64
 4   CLOSE PRICE (Rs.)         14300 non-null  float64
 5   OPEN PRICE (Rs.)          14300 non-null  float64
 6   TRADE VOLUME (No.)        14300 non-null  float64
 7   SHARE VOLUME (No.)        14300 non-null  float64
 8   TURNOVER (Rs.)            14300 non-null  float64
 9   Sector_Index              14300 non-null  float64
 10  Exchange Rate             14300 non-null  float64
 11  YoY_Inflation_%           14300 non-null  float64
 12  Daily_Return              14300 non-null  float64
 13  Log_Return                14300 non-null  float64
 14  High_Low_Range            14300 non-null  float64
 15  Open_Close_Change         14300 non-null  float64
 16  SMA_5                     14300 non-null  float64
 17  EMA_5                     14300 non-null  float64
 18  SMA_10                    14300 non-null  float64
 19  EMA_10                    14300 non-null  float64
 20  SMA_20                    14300 non-null  float64
 21  EMA_20                    14300 non-null  float64
 22  Price_vs_EMA20_Ratio      14300 non-null  float64
 23  Vol_5Day                  14300 non-null  float64
 24  Vol_20Day                 14300 non-null  float64
 25  RSI_14                    14300 non-null  float64
 26  MACD                      14300 non-null  float64
 27  MACD_Signal               14300 non-null  float64
 28  BB_StdDev                 14300 non-null  float64
 29  BB_Upper                  14300 non-null  float64
 30  BB_Lower                  14300 non-null  float64
 31  BB_Percent_B              14300 non-null  float64
 32  ROC_10Day                 14300 non-null  float64
 33  Stochastic_K              14300 non-null  float64
 34  Stochastic_D              14300 non-null  float64
 35  Volume_Change             14300 non-null  float64
 36  SMA_5_Turnover            14300 non-null  float64
 37  Turnover_vs_SMA5          14300 non-null  float64
 38  Sector_Index_Return       14300 non-null  float64
 39  USD_LKR_Return            14300 non-null  float64
 40  Relative_Strength         14300 non-null  float64
 41  Rolling_20Day_Beta        14300 non-null  float64
 42  Day_of_Week_Sin           14300 non-null  float64
 43  Day_of_Week_Cos           14300 non-null  float64
 44  Month_Sin                 14300 non-null  float64
 45  Month_Cos                 14300 non-null  float64
 46  Is_Quarter_End_Month      14300 non-null  int64
 47  Target_Close_5Day_Ahead   14300 non-null  float64
 48  Target_Return_5Day_Ahead  14300 non-null  float64
 49  Target_Close_1Day_Ahead   14300 non-null  float64
 50  Target_Return_1Day_Ahead  14300 non-null  float64
 51  Target_Close_2Day_Ahead   14300 non-null  float64
 52  Target_Return_2Day_Ahead  14300 non-null  float64
 53  Target_Close_3Day_Ahead   14300 non-null  float64
 54  Target_Return_3Day_Ahead  14300 non-null  float64
 55  Target_Close_4Day_Ahead   14300 non-null  float64
 56  Target_Return_4Day_Ahead  14300 non-null  float64
dtypes: datetime64[ns](1), float64(54), int64(1), object(1)
memory usage: 6.3+ MB

Final check for NaNs in the entire DataFrame:
0

### Step 11: Check for Redundant Features (High Correlation)

To further streamline our dataset and mitigate multicollinearity, we will examine the correlations between all engineered features. Features that are highly correlated (e.g., absolute correlation coefficient > 0.95) often provide redundant information, and one can be removed without significant loss of predictive power. This step helps in model interpretability and can prevent issues in some machine learning algorithms.

In [33]:
import numpy as np

# Exclude non-feature columns (identifiers, date) and target variables
features_to_check = [col for col in merged_df.columns if col not in [
    'COMPANY ID', 'Date',
    'Target_Close_5Day_Ahead', 'Target_Return_5Day_Ahead'
]]

# Create a DataFrame with only the features
features_df = merged_df[features_to_check].copy()

# Calculate the correlation matrix
correlation_matrix = features_df.corr().abs()

# Select upper triangle of correlation matrix to avoid duplicates and self-correlation
upper_tri = correlation_matrix.where(np.triu(np.ones(correlation_matrix.shape), k=1).astype(bool))

# Find features with correlation greater than 0.95
highly_correlated_pairs = []
for i in range(len(upper_tri.columns)):
    for j in range(i):
        if upper_tri.iloc[i, j] > 0.95:
            highly_correlated_pairs.append((upper_tri.columns[i], upper_tri.columns[j], upper_tri.iloc[i, j]))

if not highly_correlated_pairs:
    print("No highly correlated feature pairs (above 0.95) found.")
else:
    print("Highly correlated feature pairs (absolute correlation > 0.95):")
    for f1, f2, corr_val in highly_correlated_pairs:
        print(f"- {f1} and {f2}: {corr_val:.4f}")

    # Based on domain knowledge and common practices, select features to drop
    # Prioritize keeping more direct or widely used indicators
    features_to_drop = []

    # Example decisions based on typical financial feature engineering:
    # Price components: Keep CLOSE PRICE, drop others if highly correlated
    if ('PRICE HIGH (Rs.)', 'CLOSE PRICE (Rs.)', correlation_matrix.loc['PRICE HIGH (Rs.)', 'CLOSE PRICE (Rs.)']) in highly_correlated_pairs:
        if 'PRICE HIGH (Rs.)' not in features_to_drop: features_to_drop.append('PRICE HIGH (Rs.)')
    if ('PRICE LOW (Rs.)', 'CLOSE PRICE (Rs.)', correlation_matrix.loc['PRICE LOW (Rs.)', 'CLOSE PRICE (Rs.)']) in highly_correlated_pairs:
        if 'PRICE LOW (Rs.)' not in features_to_drop: features_to_drop.append('PRICE LOW (Rs.)')
    if ('OPEN PRICE (Rs.)', 'CLOSE PRICE (Rs.)', correlation_matrix.loc['OPEN PRICE (Rs.)', 'CLOSE PRICE (Rs.)']) in highly_correlated_pairs:
        if 'OPEN PRICE (Rs.)' not in features_to_drop: features_to_drop.append('OPEN PRICE (Rs.)')

    # Moving Averages: EMA is often preferred for responsiveness; BB_Middle is an SMA
    if 'SMA_20' in features_to_check and 'EMA_20' in features_to_check and correlation_matrix.loc['SMA_20', 'EMA_20'] > 0.95:
        if 'SMA_20' not in features_to_drop: features_to_drop.append('SMA_20')
    if 'SMA_10' in features_to_check and 'EMA_10' in features_to_check and correlation_matrix.loc['SMA_10', 'EMA_10'] > 0.95:
        if 'SMA_10' not in features_to_drop: features_to_drop.append('SMA_10')
    if 'SMA_5' in features_to_check and 'EMA_5' in features_to_check and correlation_matrix.loc['SMA_5', 'EMA_5'] > 0.95:
        if 'SMA_5' not in features_to_drop: features_to_drop.append('SMA_5')

    # Bollinger Bands: BB_Middle is effectively an SMA; BB_Upper/Lower are derivatives.
    # BB_Percent_B is a normalized oscillator and often more useful.
    if 'BB_Middle' in features_to_check and 'EMA_20' in features_to_check and correlation_matrix.loc['BB_Middle', 'EMA_20'] > 0.95:
        if 'BB_Middle' not in features_to_drop: features_to_drop.append('BB_Middle')
    if 'BB_Upper' in features_to_check and 'CLOSE PRICE (Rs.)' in features_to_check and correlation_matrix.loc['BB_Upper', 'CLOSE PRICE (Rs.)'] > 0.95:
        if 'BB_Upper' not in features_to_drop: features_to_drop.append('BB_Upper')
    if 'BB_Lower' in features_to_check and 'CLOSE PRICE (Rs.)' in features_to_check and correlation_matrix.loc['BB_Lower', 'CLOSE PRICE (Rs.)'] > 0.95:
        if 'BB_Lower' not in features_to_drop: features_to_drop.append('BB_Lower')
    if 'BB_StdDev' in features_to_check and 'Vol_20Day' in features_to_check and correlation_matrix.loc['BB_StdDev', 'Vol_20Day'] > 0.95:
        # Both measure 20-day volatility. Keep Vol_20Day as it's a more direct measure of return std dev.
        if 'BB_StdDev' not in features_to_drop: features_to_drop.append('BB_StdDev')

    # Volume/Turnover: Turnover captures both price and volume.
    if 'SHARE VOLUME (No.)' in features_to_check and 'TURNOVER (Rs.)' in features_to_check and correlation_matrix.loc['SHARE VOLUME (No.)', 'TURNOVER (Rs.)'] > 0.95:
        if 'SHARE VOLUME (No.)' not in features_to_drop: features_to_drop.append('SHARE VOLUME (No.)')

    # Stochastic: D is a smoothed K
    if 'Stochastic_K' in features_to_check and 'Stochastic_D' in features_to_check and correlation_matrix.loc['Stochastic_K', 'Stochastic_D'] > 0.95:
        # Keep D as it's typically used as the signal line and is smoother
        if 'Stochastic_K' not in features_to_drop: features_to_drop.append('Stochastic_K')

    # Calendar features: Keep sin/cos, drop raw numeric
    if 'Day_of_Week' in features_to_check and ('Day_of_Week_Sin' in features_to_check or 'Day_of_Week_Cos' in features_to_check):
        if 'Day_of_Week' not in features_to_drop: features_to_drop.append('Day_of_Week')
    if 'Month' in features_to_check and ('Month_Sin' in features_to_check or 'Month_Cos' in features_to_check):
        if 'Month' not in features_to_drop: features_to_drop.append('Month')

    # MACD related: MACD_Signal is derived from MACD
    if 'MACD_Signal' in features_to_check and 'MACD' in features_to_check and correlation_matrix.loc['MACD_Signal', 'MACD'] > 0.95:
        # Keeping MACD and MACD_Signal is standard for MACD crossover strategies, but if one must be dropped for high corr, keep MACD.
        # However, for MACD, typically both are kept for crossover signals. Let's not drop one of them right now unless the correlation is extremely high and causes issues.
        pass # Decide to keep both for now, unless specific instruction to drop one.

    # Remove duplicates from the list of features to drop
    features_to_drop = list(set(features_to_drop))

    if features_to_drop:
        print(f"\nRecommended features to drop due to high correlation: {features_to_drop}")
        merged_df.drop(columns=features_to_drop, inplace=True)
        print(f"Dropped {len(features_to_drop)} features.")
    else:
        print("\nNo features recommended for dropping based on current criteria or manual selection.")

print("\nShape of DataFrame after correlation-based feature reduction:", merged_df.shape)
print("\nFinal DataFrame head after feature reduction:")
display(merged_df.head())
print("\nFinal DataFrame info after feature reduction:")
merged_df.info()

No highly correlated feature pairs (above 0.95) found.

Shape of DataFrame after correlation-based feature reduction: (14300, 57)

Final DataFrame head after feature reduction:

,COMPANY ID,Date,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.),Sector_Index,...,Target_Close_5Day_Ahead,Target_Return_5Day_Ahead,Target_Close_1Day_Ahead,Target_Return_1Day_Ahead,Target_Close_2Day_Ahead,Target_Return_2Day_Ahead,Target_Close_3Day_Ahead,Target_Return_3Day_Ahead,Target_Close_4Day_Ahead,Target_Return_4Day_Ahead
475,ABL,2020-03-04,23.0,22.0,23.0,22.0,1.6,20293.5,446860.5,516.085791,...,22.0,-0.043478,23.0,0.000000,21.0,-0.086957,22.0,-0.043478,22.0,-0.043478
489,ABL,2020-03-05,23.0,22.0,23.0,23.0,1.1,600.4,13309.1,509.383378,...,20.0,-0.130435,21.0,-0.086957,22.0,-0.043478,22.0,-0.043478,22.0,-0.043478
503,ABL,2020-03-06,22.0,21.0,21.0,21.0,1.7,17043.8,372170.5,502.680965,...,19.0,-0.095238,22.0,0.047619,22.0,0.047619,22.0,0.047619,20.0,-0.047619
510,ABL,2020-03-10,22.0,20.0,22.0,22.0,3.7,15695.5,332562.2,482.573727,...,18.0,-0.181818,22.0,0.000000,22.0,0.000000,20.0,-0.090909,19.0,-0.136364
524,ABL,2020-03-11,22.0,21.0,22.0,22.0,1.1,5150.5,109561.0,495.978552,...,18.0,-0.181818,22.0,0.000000,20.0,-0.090909,19.0,-0.136364,18.0,-0.181818

Final DataFrame info after feature reduction:
<class 'pandas.core.frame.DataFrame'>
Index: 14300 entries, 475 to 14790
Data columns (total 57 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   COMPANY ID                14300 non-null  object
 1   Date                      14300 non-null  datetime64[ns]
 2   PRICE HIGH (Rs.)          14300 non-null  float64
 3   PRICE LOW (Rs.)           14300 non-null  float64
 4   CLOSE PRICE (Rs.)         14300 non-null  float64
 5   OPEN PRICE (Rs.)          14300 non-null  float64
 6   TRADE VOLUME (No.)        14300 non-null  float64
 7   SHARE VOLUME (No.)        14300 non-null  float64
 8   TURNOVER (Rs.)            14300 non-null  float64
 9   Sector_Index              14300 non-null  float64
 10  Exchange Rate             14300 non-null  float64
 11  YoY_Inflation_%           14300 non-null  float64
 12  Daily_Return              14300 non-null  float64
 13  Log_Return                14300 non-null  float64
 14  High_Low_Range            14300 non-null  float64
 15  Open_Close_Change         14300 non-null  float64
 16  SMA_5                     14300 non-null  float64
 17  EMA_5                     14300 non-null  float64
 18  SMA_10                    14300 non-null  float64
 19  EMA_10                    14300 non-null  float64
 20  SMA_20                    14300 non-null  float64
 21  EMA_20                    14300 non-null  float64
 22  Price_vs_EMA20_Ratio      14300 non-null  float64
 23  Vol_5Day                  14300 non-null  float64
 24  Vol_20Day                 14300 non-null  float64
 25  RSI_14                    14300 non-null  float64
 26  MACD                      14300 non-null  float64
 27  MACD_Signal               14300 non-null  float64
 28  BB_StdDev                 14300 non-null  float64
 29  BB_Upper                  14300 non-null  float64
 30  BB_Lower                  14300 non-null  float64
 31  BB_Percent_B              14300 non-null  float64
 32  ROC_10Day                 14300 non-null  float64
 33  Stochastic_K              14300 non-null  float64
 34  Stochastic_D              14300 non-null  float64
 35  Volume_Change             14300 non-null  float64
 36  SMA_5_Turnover            14300 non-null  float64
 37  Turnover_vs_SMA5          14300 non-null  float64
 38  Sector_Index_Return       14300 non-null  float64
 39  USD_LKR_Return            14300 non-null  float64
 40  Relative_Strength         14300 non-null  float64
 41  Rolling_20Day_Beta        14300 non-null  float64
 42  Day_of_Week_Sin           14300 non-null  float64
 43  Day_of_Week_Cos           14300 non-null  float64
 44  Month_Sin                 14300 non-null  float64
 45  Month_Cos                 14300 non-null  float64
 46  Is_Quarter_End_Month      14300 non-null  int64
 47  Target_Close_5Day_Ahead   14300 non-null  float64
 48  Target_Return_5Day_Ahead  14300 non-null  float64
 49  Target_Close_1Day_Ahead   14300 non-null  float64
 50  Target_Return_1Day_Ahead  14300 non-null  float64
 51  Target_Close_2Day_Ahead   14300 non-null  float64
 52  Target_Return_2Day_Ahead  14300 non-null  float64
 53  Target_Close_3Day_Ahead   14300 non-null  float64
 54  Target_Return_3Day_Ahead  14300 non-null  float64
 55  Target_Close_4Day_Ahead   14300 non-null  float64
 56  Target_Return_4Day_Ahead  14300 non-null  float64
dtypes: datetime64[ns](1), float64(54), int64(1), object(1)
memory usage: 6.3+ MB

In [34]:
# --- Drop redundant / duplicate columns before saving ---
# BB_Middle is an exact duplicate of SMA_20 (both are the 20-day SMA of Close, r = 1.0)
# Day_of_Week and Month are the raw ordinal versions already captured by their sin/cos encodings
cols_to_drop = ['BB_Middle', 'Day_of_Week', 'Month']
cols_to_drop = [c for c in cols_to_drop if c in merged_df.columns]  # only drop what's actually present

merged_df.drop(columns=cols_to_drop, inplace=True)

print(f"Dropped: {cols_to_drop}")
print("Shape after cleanup:", merged_df.shape)

Dropped: []
Shape after cleanup: (14300, 57)

### Step 12: Split and Scale Data

In [37]:
from sklearn.preprocessing import StandardScaler

train_end_date = pd.to_datetime('2023-12-31')
val_end_date = pd.to_datetime('2024-12-31')

train_df = merged_df[merged_df['Date'] <= train_end_date]
val_df = merged_df[(merged_df['Date'] > train_end_date) & (merged_df['Date'] <= val_end_date)]
test_df = merged_df[merged_df['Date'] > val_end_date]

print(f"Training set shape: {train_df.shape}")
print(f"Validation set shape: {val_df.shape}")
print(f"Test set shape: {test_df.shape}")

# Exclude identifiers AND every target column (any horizon), not just the original two
features_cols = [col for col in merged_df.columns
                  if col not in ['COMPANY ID', 'Date'] and not col.startswith('Target_')]
target_cols = [f'Target_Return_{h}Day_Ahead' for h in range(1, 6)]  # t+1 ... t+5, in order

X_train = train_df[features_cols]
y_train = train_df[target_cols]
X_val = val_df[features_cols]
y_val = val_df[target_cols]
X_test = test_df[features_cols]
y_test = test_df[target_cols]

company_id_train = train_df['COMPANY ID']
company_id_val = val_df['COMPANY ID']
company_id_test = test_df['COMPANY ID']

scalers = {}
scaled_X_train_list, scaled_X_val_list, scaled_X_test_list = [], [], []

for company_id in merged_df['COMPANY ID'].unique():
    X_train_company = X_train[company_id_train == company_id]
    X_val_company = X_val[company_id_val == company_id]
    X_test_company = X_test[company_id_test == company_id]

    if not X_train_company.empty:
        scaler = StandardScaler()
        scaler.fit(X_train_company)
        scalers[company_id] = scaler

        def attach_ids(scaled_array, source_df, index):
            out = pd.DataFrame(scaled_array, columns=features_cols, index=index)
            out.insert(0, 'Date', source_df.loc[index, 'Date'].values)
            out.insert(0, 'COMPANY ID', company_id)
            return out

        scaled_X_train_list.append(attach_ids(scaler.transform(X_train_company), train_df, X_train_company.index))
        if not X_val_company.empty:
            scaled_X_val_list.append(attach_ids(scaler.transform(X_val_company), val_df, X_val_company.index))
        if not X_test_company.empty:
            scaled_X_test_list.append(attach_ids(scaler.transform(X_test_company), test_df, X_test_company.index))
    else:
        print(f"Warning: Company {company_id} has no training data. Skipping.")

X_train_scaled = pd.concat(scaled_X_train_list).sort_index()
X_val_scaled = pd.concat(scaled_X_val_list).sort_index()
X_test_scaled = pd.concat(scaled_X_test_list).sort_index()

y_train = y_train.loc[X_train_scaled.index].copy()
y_val = y_val.loc[X_val_scaled.index].copy()
y_test = y_test.loc[X_test_scaled.index].copy()

print(f"X_train_scaled: {X_train_scaled.shape}, y_train: {y_train.shape}")
print(f"X_val_scaled: {X_val_scaled.shape}, y_val: {y_val.shape}")
print(f"X_test_scaled: {X_test_scaled.shape}, y_test: {y_test.shape}")
X_train_scaled.head()

Training set shape: (8269, 57)
Validation set shape: (3067, 57)
Test set shape: (2964, 57)
Warning: Company CBNK has no training data. Skipping.
X_train_scaled: (8269, 47), y_train: (8269, 5)
X_val_scaled: (2852, 47), y_val: (2852, 5)
X_test_scaled: (2736, 47), y_test: (2736, 5)

,COMPANY ID,Date,PRICE HIGH (Rs.),PRICE LOW (Rs.),CLOSE PRICE (Rs.),OPEN PRICE (Rs.),TRADE VOLUME (No.),SHARE VOLUME (No.),TURNOVER (Rs.),Sector_Index,...,Turnover_vs_SMA5,Sector_Index_Return,USD_LKR_Return,Relative_Strength,Rolling_20Day_Beta,Day_of_Week_Sin,Day_of_Week_Cos,Month_Sin,Month_Cos,Is_Quarter_End_Month
468,COMB,2020-03-04,0.679026,0.686727,0.613780,0.763342,-0.220667,-0.306856,-0.374031,-1.779732,...,-0.799159,-0.850024,-0.071747,0.359066,0.604155,1.195828,-0.189309,1.381416,-0.003074,1.297458
469,NDB,2020-03-04,1.499397,1.436536,1.381628,1.571861,-0.490364,-0.262709,-0.239914,-1.779732,...,0.308139,-0.850024,-0.071747,-0.177603,0.818769,1.195828,-0.189309,1.381416,-0.003074,1.297458
470,SEYB,2020-03-04,0.363297,0.521895,0.410570,0.471912,-0.423275,-0.206587,-0.216162,-1.779454,...,-0.894611,-0.847867,-0.072042,0.240060,0.418654,1.192098,-0.195554,1.381250,-0.002635,1.295490
471,NTB,2020-03-04,0.504546,0.516806,0.484839,0.536229,-0.705808,-0.184070,-0.218996,-1.788181,...,3.717498,-0.844054,-0.071974,0.805219,-0.808797,1.195442,-0.189128,1.384238,-0.004077,1.292987
473,SAMP,2020-03-04,0.074513,0.060059,0.011619,0.145020,0.272404,-0.232556,-0.207784,-1.775365,...,0.123858,-0.848976,-0.072044,0.000096,-0.474627,1.192707,-0.190545,1.390169,-0.003081,1.305038

### Step 13: Save Prepared Data

In [39]:
# Define file paths for saving
output_full_df_path = '/content/final_feature_engineered_data.csv'
output_X_train_path = '/content/X_train_scaled.csv'
output_y_train_path = '/content/y_train.csv'
output_X_val_path = '/content/X_val_scaled.csv'
output_y_val_path = '/content/y_val.csv'
output_X_test_path = '/content/X_test_scaled.csv'
output_y_test_path = '/content/y_test.csv'

# Save the full merged_df
merged_df.to_csv(output_full_df_path, index=False)
print(f"Full engineered data saved to {output_full_df_path}")

# Save the training set
X_train_scaled.to_csv(output_X_train_path, index=False)  # COMPANY ID and Date are now real columns
y_train.to_csv(output_y_train_path, index=True)
print(f"Scaled training features saved to {output_X_train_path}")
print(f"Training target saved to {output_y_train_path}")

# Save the validation set
X_val_scaled.to_csv(output_X_val_path, index=False)
y_val.to_csv(output_y_val_path, index=True)
print(f"Scaled validation features saved to {output_X_val_path}")
print(f"Validation target saved to {output_y_val_path}")

# Save the test set
X_test_scaled.to_csv(output_X_test_path, index=False)
y_test.to_csv(output_y_test_path, index=True)
print(f"Scaled test features saved to {output_X_test_path}")
print(f"Test target saved to {output_y_test_path}")

Full engineered data saved to /content/final_feature_engineered_data.csv
Scaled training features saved to /content/X_train_scaled.csv
Training target saved to /content/y_train.csv
Scaled validation features saved to /content/X_val_scaled.csv
Validation target saved to /content/y_val.csv
Scaled test features saved to /content/X_test_scaled.csv
Test target saved to /content/y_test.csv